import { BEREICHE, STATIONEN, TIERE, TOUREN, FUETTERUNGEN, OEFFNUNG } from '../app/data.js';
import * as GEO from '../app/mapgeo.js';

const app = document.querySelector('#app');
const KEY = 'hagenbeck-v24';
const ICON = {haupteingang:'🎟️',flamingoteich:'🦩',elefanten:'🐘',orangutans:'🦧',tiger:'🐅',loewen:'🦁',afrikapanorama:'🦒',strausse:'🦓',eismeer:'🐧',seeloewen:'🦭',kamele:'🐫',alpakas:'🦦',streichelgehege:'🐐',spielplatz:'🛝',japangarten:'🌿',tropenaquarium:'🐠'};
const DEFAULT = {view:'home',filter:'alle',selected:null,scale:1,x:0,y:0,location:null,route:[],tour:null,visited:[],favorites:[],times:{},budget:180,group:'family',started:Date.now(),labels:true};
let S = load();
let installPrompt = null;
let toastTimer;

function load(){try{return {...DEFAULT,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return {...DEFAULT}}}
function save(){try{localStorage.setItem(KEY,JSON.stringify({...S,selected:null,x:0,y:0,scale:1}))}catch{}}
function set(patch,draw=true){S={...S,...patch};save();if(draw)render()}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function st(id){return STATIONEN.find(x=>x.id===id)}
function tr(id){return TOUREN.find(x=>x.id===id)}
function closePath(p){return p.map((x,i)=>`${i?'L':'M'}${x[0].toFixed(2)} ${x[1].toFixed(2)}`).join(' ')+' Z'}
function openPath(p){return p.map((x,i)=>`${i?'L':'M'}${x[0].toFixed(2)} ${x[1].toFixed(2)}`).join(' ')}
function nowMin(){const d=new Date();return d.getHours()*60+d.getMinutes()}
function opening(){const d=new Date(),m=d.getMonth()+1,day=d.getDate(),md=m*100+day;const special=OEFFNUNG.sondertage?.[`${String(day).padStart(2,'0')}.${String(m).padStart(2,'0')}.`];if(special)return special;for(const r of OEFFNUNG.regeln||[]){if(r.monate?.includes(m))return r.zeit;if(r.vonTag&&md>=r.vonTag[0]*100+r.vonTag[1]&&md<=r.bisTag[0]*100+r.bisTag[1])return r.zeit}return ''}
function remaining(){const matches=[...opening().matchAll(/(\d{1,2}):(\d{2})/g)];if(matches.length<2)return null;return Math.max(0,Number(matches[1][1])*60+Number(matches[1][2])-nowMin())}
function duration(n){if(n==null)return 'unbekannt';if(n<60)return `${n} Min.`;const h=Math.floor(n/60),r=n%60;return r?`${h} Std. ${r} Min.`:`${h} Std.`}
function start(){if(S.location)return S.location;const e=st('haupteingang');return{x:e.mapX,y:e.mapY}}
function meters(s){const p=start();return Math.round(Math.hypot(s.mapX-p.x,s.mapY-p.y)*GEO.MASS.meterProEinheit)}
function walk(s){return Math.max(1,Math.ceil(meters(s)/72))}
function nextFeeding(){return FUETTERUNGEN.map(f=>{const time=S.times[f.id]||f.zeit;if(!time)return null;const [h,m]=time.split(':').map(Number);return{...f,time,inMin:h*60+m-nowMin()}}).filter(x=>x&&x.inMin>=-10).sort((a,b)=>a.inMin-b.inMin)[0]||null}
function unvisited(){return STATIONEN.filter(x=>!S.visited.includes(x.id))}
function recommendation(){const f=nextFeeding();if(f&&f.inMin<=45){const s=st(f.station);return{tag:'Zeitkritisch',title:f.titel,detail:`${f.time} Uhr · ${walk(s)} Min. zu Fuß`,text:f.inMin<=15?'Jetzt direkt losgehen.':'Passt ideal als nächster Programmpunkt.',station:s}}const s=unvisited().filter(x=>S.filter==='alle'||x.bereich===S.filter).sort((a,b)=>meters(a)-meters(b))[0]||st('elefanten');return{tag:'Als Nächstes',title:s.name,detail:`${meters(s)} m · etwa ${walk(s)} Min.`,text:s.tipp||'Liegt günstig auf deinem weiteren Weg.',station:s}}
function progress(){return Math.round(S.visited.length/STATIONEN.length*100)}
function nav(){return `<nav class="bottom-nav">${[['home','⌂','Heute'],['map','🗺️','Karte'],['plan','✨','Plan'],['pass','🏅','Tierpass']].map(([v,i,l])=>`<button class="${S.view===v?'active':''}" data-view="${v}"><b>${i}</b><small>${l}</small></button>`).join('')}</nav>`}
function top(){return `<header class="topbar"><button class="brand" data-view="home"><span class="brand-mark">H</span><span><strong>Hagenbeck erleben</strong><small>V2.4 · ${remaining()==null?'Tagesbegleiter':`noch ${duration(remaining())}`}</small></span></button><div class="top-actions">${installPrompt?'<button class="round" data-action="install">↓</button>':''}<button class="round" data-action="locate">◎</button></div></header>`}
function render(){app.innerHTML=`<div class="shell">${top()}${S.view==='home'?home():S.view==='map'?mapView():S.view==='plan'?plan():passView()}${nav()}${sheet()}<div id="toast" class="toast"></div></div>`;bind()}

function home(){const r=recommendation(),f=nextFeeding();return `<main class="home"><section class="hero"><div class="hero-art"><span>${ICON[r.station.id]||'🦒'}</span></div><div class="hero-copy"><em>${greeting()}</em><h1>Dein Tag im Tierpark</h1><p>${opening()?`Heute geöffnet: ${esc(opening())}`:'Plane deinen Besuch nach deinen Interessen.'}</p><div class="actions"><button class="primary" data-view="map">Karte öffnen</button><button class="glass" data-view="plan">Tag planen</button></div></div></section><section class="dashboard"><div class="stat"><b>${S.visited.length}</b><span>entdeckt</span></div><div class="stat"><b>${progress()}%</b><span>Tierpass</span></div><div class="stat"><b>${remaining()==null?'–':duration(remaining())}</b><span>bis Schluss</span></div></section><section class="recommend card"><div class="rec-icon">${ICON[r.station.id]||'📍'}</div><div><em>${r.tag}</em><h2>${esc(r.title)}</h2><p>${esc(r.detail)}</p><small>${esc(r.text)}</small></div><button class="arrow" data-station="${r.station.id}">›</button></section>${f?`<section class="event card"><span>⏰</span><div><em>Nächster Termin</em><h3>${esc(f.titel)}</h3><p>${f.time} Uhr · in ${Math.max(0,f.inMin)} Minuten</p></div><button data-station="${f.station}">Auf Karte</button></section>`:''}<section class="section"><div class="section-head"><div><em>In deiner Nähe</em><h2>Jetzt entdecken</h2></div><button data-view="map">Alle anzeigen</button></div><div class="nearby">${unvisited().sort((a,b)=>meters(a)-meters(b)).slice(0,4).map(placeCard).join('')}</div></section><section class="journey"><em>Dein Fortschritt</em><h2>${S.visited.length?'Heute schon viel erlebt':'Das Abenteuer beginnt'}</h2><div class="bar"><i style="width:${progress()}%"></i></div><p>${S.visited.length} von ${STATIONEN.length} Stationen entdeckt</p><button class="secondary" data-view="pass">Tierpass öffnen</button></section></main>`}
function greeting(){const h=new Date().getHours();return h<11?'Guten Morgen':h<17?'Schönen Besuch':'Guten Abend'}
function placeCard(s){return `<button class="place" data-station="${s.id}"><span>${ICON[s.id]||'📍'}</span><strong>${esc(s.name)}</strong><small>${meters(s)} m · ${walk(s)} Min.</small></button>`}

function routeD(){const pts=S.route.map(st).filter(Boolean).map(x=>[x.mapX,x.mapY]);return pts.length>1?openPath(pts):''}
function mapSvg(){const areas=GEO.GEHEGE.map(g=>`<path d="${closePath(g.punkte)}" fill="${BEREICHE[g.bereich]?.farbe||'#78906b'}" opacity=".46"/>`).join('');const water=GEO.WASSER.map(w=>`<path d="${closePath(w.punkte)}" fill="#72bed2" opacity=".9"/>`).join('');const ways=GEO.WEGE.map(w=>`<path d="${openPath(w)}" class="park-way"/>`).join('');const buildings=GEO.GEBAEUDE.map(g=>`<path d="${closePath(g.punkte)}" class="building"/>`).join('');const trees=GEO.BAEUME.slice(0,240).map(b=>`<circle cx="${b[0]}" cy="${b[1]}" r="${Math.max(.3,(b[2]||1)*.3)}" class="tree"/>`).join('');const markers=STATIONEN.map(s=>`<g class="marker ${S.filter!=='alle'&&S.filter!==s.bereich?'dim':''} ${S.visited.includes(s.id)?'visited':''}" data-station="${s.id}" transform="translate(${s.mapX} ${s.mapY})"><circle class="halo" r="4.6"/><circle class="pin" r="3.2" fill="${BEREICHE[s.bereich]?.farbe||'#7fbd50'}"/><text y="1.15">${ICON[s.id]||'📍'}</text>${S.labels?`<text class="label" y="7">${esc(s.name)}</text>`:''}</g>`).join('');const loc=S.location?`<g transform="translate(${S.location.x} ${S.location.y})"><circle class="pulse" r="3"/><circle class="me" r="2"/></g>`:'';return `<svg viewBox="-2 -2 104 ${GEO.MASS.h+4}"><defs><linearGradient id="ground" x1="0" y1="0" x2="0" y2="1"><stop stop-color="#bad3a8"/><stop offset="1" stop-color="#799b69"/></linearGradient><filter id="shadow"><feDropShadow dx="0" dy="1" stdDeviation="1" flood-opacity=".32"/></filter></defs><rect x="-2" y="-2" width="104" height="${GEO.MASS.h+4}" fill="#173424"/><path d="${closePath(GEO.GRENZE)}" fill="url(#ground)"/>${areas}${water}${ways}${trees}${buildings}${S.route.length>1?`<path class="route-line" d="${routeD()}"/>`:''}${markers}${loc}</svg>`}
function mapView(){return `<main class="map" id="viewport"><div class="map-shade"></div><div class="filters">${[['alle','Alle'],['eismeer','Eismeer'],['afrika','Afrika'],['asien','Asien'],['kinder','Kinder'],['tropen','Indoor']].map(([k,l])=>`<button class="${S.filter===k?'active':''}" data-filter="${k}">${l}</button>`).join('')}</div><div class="tools"><button data-action="zoom-in">＋</button><button data-action="zoom-out">−</button><button data-action="reset-map">⌂</button><button data-action="toggle-labels">Aa</button></div><div class="map-stage" id="mapStage" style="transform:translate(${S.x}px,${S.y}px) scale(${S.scale})">${mapSvg()}</div><div class="map-status"><em>${S.route.length?'Route aktiv':'Erlebnis-Karte'}</em><strong>${S.tour?tr(S.tour)?.titel:'Tippe auf eine Station'}</strong><small>${S.route.length?`${S.route.filter(id=>!S.visited.includes(id)).length} Ziele noch offen`:'Zoom, Standort und Filter verwenden'}</small></div></main>`}

function plannerRecommendations(){let list=TOUREN.filter(t=>t.minuten<=S.budget+30);const words={family:['famil','kind'],adult:['klass','afrika','raub'],accessible:['barriere','entspannt'],rain:['regen','innen']};const w=words[S.group]||[];return list.sort((a,b)=>Number(w.some(x=>(a.id+a.titel+a.schwerpunkt).toLowerCase().includes(x)))-Number(w.some(x=>(b.id+b.titel+b.schwerpunkt).toLowerCase().includes(x)))).reverse().slice(0,3)}
function plan(){return `<main class="panel"><section class="panel-hero"><em>V2.2 · intelligenter Besuch</em><h1>Plane deinen perfekten Tag</h1><p>Die Empfehlung berücksichtigt Zeit, Besuchergruppe, Parkschluss und deine eingegebenen Programmpunkte.</p></section><section class="form card"><label>Wie viel Zeit habt ihr?<select id="budget"><option value="60" ${S.budget===60?'selected':''}>Bis 1 Stunde</option><option value="120" ${S.budget===120?'selected':''}>Etwa 2 Stunden</option><option value="180" ${S.budget===180?'selected':''}>Etwa 3 Stunden</option><option value="300" ${S.budget===300?'selected':''}>Fast den ganzen Tag</option></select></label><label>Wer ist dabei?<select id="group"><option value="family" ${S.group==='family'?'selected':''}>Familie mit Kindern</option><option value="adult" ${S.group==='adult'?'selected':''}>Erwachsene</option><option value="accessible" ${S.group==='accessible'?'selected':''}>Barrierearm unterwegs</option><option value="rain" ${S.group==='rain'?'selected':''}>Regenwetter</option></select></label></section><section class="section"><div class="section-head"><div><em>Deine Auswahl</em><h2>Passende Touren</h2></div></div><div class="tour-list">${plannerRecommendations().map(t=>`<article class="tour-card"><span>${t.emoji||'✨'}</span><div><em>${esc(t.schwerpunkt)}</em><h2>${esc(t.titel)}</h2><p>${esc(t.beschreibung)}</p><div><small>⏱ ${t.minuten} Min.</small><small>📍 ${t.stationen.length} Stationen</small><small>🚶 ${esc(t.laenge||'Rundweg')}</small></div><button class="primary" data-tour="${t.id}">Tour starten</button></div></article>`).join('')}</div></section><section class="section"><div class="section-head"><div><em>Tagesaktuell</em><h2>Fütterungen eintragen</h2></div><button data-action="clear-times">Leeren</button></div><p class="muted">Zeiten vom Aushang am Eingang übernehmen. Die App merkt sie sich und priorisiert den nächsten Termin.</p><div class="feeding-list">${FUETTERUNGEN.map(f=>`<label><span><b>${esc(f.titel)}</b><small>${esc(st(f.station)?.name||'')}</small></span><input type="time" data-time="${f.id}" value="${esc(S.times[f.id]||f.zeit)}"></label>`).join('')}</div></section></main>`}

function passView(){return `<main class="panel"><section class="panel-hero passport"><em>V2.3 · Entdecken und sammeln</em><h1>Dein Tierpass</h1><p>${S.visited.length} von ${STATIONEN.length} Stempeln gesammelt.</p><div class="bar"><i style="width:${progress()}%"></i></div></section><section class="stamps">${STATIONEN.map(s=>`<button class="stamp ${S.visited.includes(s.id)?'done':''}" data-station="${s.id}"><span>${S.visited.includes(s.id)?ICON[s.id]||'✓':'?'}</span><b>${esc(s.name)}</b><small>${S.visited.includes(s.id)?'Entdeckt':'Noch offen'}</small></button>`).join('')}</section><section class="section"><div class="section-head"><div><em>Kleine Missionen</em><h2>Park-Quests</h2></div></div><div class="quests">${quests().map(q=>`<article class="${q.done?'done':''}"><span>${q.done?'✓':q.icon}</span><div><b>${q.title}</b><p>${q.text}</p></div></article>`).join('')}</div></section><section class="summary card"><em>Tagesrückblick</em><h2>${S.visited.length?'Das habt ihr geschafft':'Euer Abenteuer wartet'}</h2><p>${summary()}</p>${S.visited.length?'<button class="secondary" data-action="reset-progress">Neuen Besuch starten</button>':'<button class="primary" data-view="map">Erste Entdeckung machen</button>'}</section></main>`}
function quests(){const v=new Set(S.visited);return [{icon:'🧊',title:'Polarforscher',text:'Besuche Eismeer und Seebären.',done:v.has('eismeer')&&v.has('seeloewen')},{icon:'🦒',title:'Afrika-Panorama',text:'Entdecke Löwen, Savanne und Steppenweg.',done:['loewen','afrikapanorama','strausse'].every(x=>v.has(x))},{icon:'🌿',title:'Ruheinsel',text:'Mache eine Pause im Japanischen Garten.',done:v.has('japangarten')},{icon:'🐘',title:'Die großen Klassiker',text:'Elefanten, Tiger und Eismeer an einem Tag.',done:['elefanten','tiger','eismeer'].every(x=>v.has(x))}]}
function summary(){if(!S.visited.length)return 'Öffne die Karte und sammle deinen ersten Stempel.';const mins=Math.max(1,Math.round((Date.now()-S.started)/60000));const animals=new Set(S.visited.flatMap(id=>st(id)?.tiere||[])).size;return `Ihr wart etwa ${duration(mins)} unterwegs, habt ${S.visited.length} Stationen und ungefähr ${animals} Tierarten entdeckt.`}

function sheet(){if(!S.selected)return'';const s=st(S.selected),visited=S.visited.includes(s.id),fav=S.favorites.includes(s.id);return `<section class="sheet open"><div class="handle"></div><div class="sheet-head"><div class="big-icon">${ICON[s.id]||'📍'}</div><div><em>${esc(BEREICHE[s.bereich]?.name||'Station')} · ${meters(s)} m</em><h2>${esc(s.name)}</h2><small>etwa ${walk(s)} Min. entfernt · ${s.dauer} Min. Aufenthalt</small></div><button data-action="close-sheet">×</button></div><p>${esc(s.beschreibung)}</p>${s.tipp?`<aside><b>Beobachtungstipp</b>${esc(s.tipp)}</aside>`:''}<div class="sheet-actions"><button class="primary" data-action="navigate" data-id="${s.id}">Bring mich hin</button><button class="secondary" data-action="visited" data-id="${s.id}">${visited?'✓ Entdeckt':'Als entdeckt markieren'}</button><button class="heart ${fav?'active':''}" data-action="favorite" data-id="${s.id}">♥</button></div></section>`}
function toast(msg){const el=document.querySelector('#toast');if(!el)return;el.textContent=msg;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2200)}
function select(id){S.selected=id;S.view='map';save();render()}
function startTour(id){const t=tr(id);if(!t)return;set({tour:id,route:t.stationen.map(x=>x.id),selected:t.stationen[0]?.id,view:'map',scale:1,x:0,y:0});setTimeout(()=>toast(`Tour „${t.titel}“ gestartet`),0)}
function navigate(id){set({tour:null,route:['haupteingang',id],selected:id,view:'map'});setTimeout(()=>toast(`Route zu ${st(id).name} aktiviert`),0)}
function visit(id){const has=S.visited.includes(id);set({visited:has?S.visited.filter(x=>x!==id):[...S.visited,id]});setTimeout(()=>toast(has?'Stempel entfernt':'Stempel gesammelt'),0)}
function locate(){if(!navigator.geolocation){toast('Standort nicht verfügbar');return}toast('Standort wird bestimmt …');navigator.geolocation.getCurrentPosition(p=>{const x=(p.coords.longitude-GEO.OSM_BOUNDS.west)/(GEO.OSM_BOUNDS.ost-GEO.OSM_BOUNDS.west)*100,y=(GEO.OSM_BOUNDS.nord-p.coords.latitude)/(GEO.OSM_BOUNDS.nord-GEO.OSM_BOUNDS.sued)*GEO.MASS.h;set({location:{x,y},view:'map'});setTimeout(()=>toast('Standort angezeigt'),0)},()=>toast('Standort konnte nicht bestimmt werden'),{enableHighAccuracy:true,timeout:9000})}
function bind(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>set({view:b.dataset.view,selected:null}));document.querySelectorAll('[data-station]').forEach(b=>b.onclick=e=>{e.stopPropagation();select(b.dataset.station)});document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>set({filter:b.dataset.filter}));document.querySelectorAll('[data-tour]').forEach(b=>b.onclick=()=>startTour(b.dataset.tour));document.querySelectorAll('[data-time]').forEach(i=>i.onchange=()=>{S.times[i.dataset.time]=i.value;save();render()});const budget=document.querySelector('#budget');if(budget)budget.onchange=()=>set({budget:Number(budget.value),view:'plan'});const group=document.querySelector('#group');if(group)group.onchange=()=>set({group:group.value,view:'plan'});document.querySelectorAll('[data-action]').forEach(b=>b.onclick=e=>{e.stopPropagation();const a=b.dataset.action;if(a==='locate')locate();if(a==='close-sheet')set({selected:null});if(a==='navigate')navigate(b.dataset.id);if(a==='visited')visit(b.dataset.id);if(a==='favorite')set({favorites:S.favorites.includes(b.dataset.id)?S.favorites.filter(x=>x!==b.dataset.id):[...S.favorites,b.dataset.id]});if(a==='zoom-in')set({scale:Math.min(2.8,S.scale+.22)});if(a==='zoom-out')set({scale:Math.max(.78,S.scale-.22)});if(a==='reset-map')set({scale:1,x:0,y:0});if(a==='toggle-labels')set({labels:!S.labels});if(a==='clear-times')set({times:{},view:'plan'});if(a==='reset-progress')set({...DEFAULT,started:Date.now()});if(a==='install'&&installPrompt){installPrompt.prompt();installPrompt=null}});mapGestures()}
function mapGestures(){const vp=document.querySelector('#viewport'),stage=document.querySelector('#mapStage');if(!vp||!stage)return;let drag=null;vp.onpointerdown=e=>{if(e.target.closest('button,.marker'))return;drag={x:e.clientX,y:e.clientY,ox:S.x,oy:S.y};vp.setPointerCapture(e.pointerId)};vp.onpointermove=e=>{if(!drag)return;S.x=drag.ox+e.clientX-drag.x;S.y=drag.oy+e.clientY-drag.y;stage.style.transform=`translate(${S.x}px,${S.y}px) scale(${S.scale})`};vp.onpointerup=()=>{drag=null;save()};vp.addEventListener('wheel',e=>{e.preventDefault();S.scale=Math.max(.78,Math.min(2.8,S.scale+(e.deltaY<0?.12:-.12)));stage.style.transform=`translate(${S.x}px,${S.y}px) scale(${S.scale})`;save()},{passive:false})}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;render()});if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('../sw.js').catch(()=>{}));render();