/*
 * Inhaltsdaten für den Tierpark-Begleiter.
 *
 * WICHTIG / Datenpflege:
 * Tierbestand, Fütterungszeiten und Öffnungszeiten ändern sich. Die Angaben
 * hier sind ein gepflegter Startbestand für die App, keine offizielle Auskunft
 * des Tierparks. Vor dem Besuch bitte auf hagenbeck.de prüfen.
 * Die Stations-Koordinaten sind aus der schematischen Karte abgeleitet und
 * damit nur ungefähr. In den Einstellungen lässt sich jede Station vor Ort
 * per "Hier bin ich" auf die echte GPS-Position setzen.
 */

export const META = {
  stand: '05.08.2026',
  quelleHinweis:
    'Tierbestand und Zeiten können sich kurzfristig ändern. Aktuelles immer auf hagenbeck.de oder am Aushang am Eingang prüfen.',
};

/* Umgrenzendes Rechteck der Parkgrenze aus OpenStreetMap. Zusammen mit
 * MASS aus mapgeo.js rechnet es Kartenpositionen in GPS-Koordinaten um
 * (x: 0..100 West->Ost, y: 0..MASS.h Nord->Süd). */
export const PARK_BOUNDS = { nord: 53.5990236, süd: 53.5946671, west: 9.9338863, ost: 9.9422995 };

export const BEREICHE = {
  eingang: { name: 'Eingang & Wege', farbe: '#8d7b5f' },
  eismeer: { name: 'Eismeer', farbe: '#2f6f9f' },
  asien: { name: 'Asien', farbe: '#a4623a' },
  afrika: { name: 'Afrika', farbe: '#c08a2e' },
  suedamerika: { name: 'Südamerika', farbe: '#6a8f3c' },
  kinder: { name: 'Für Kinder', farbe: '#b8503f' },
  tropen: { name: 'Tropen-Aquarium', farbe: '#3f8f7a' },
  amerika: { name: 'Amerika', farbe: '#7a6ea0' },
  australien: { name: 'Australien', farbe: '#b8506e' },
  garten: { name: 'Garten & Ruhe', farbe: '#5f7f5f' },
};

/*
 * Stationen = Orte im Park. mapX/mapY sind Positionen auf der schematischen
 * Karte (0..100, links oben = 0/0). Die Karte ist eine Orientierungshilfe,
 * kein maßstabsgetreuer Lageplan.
 */
export const STATIONEN = [
  {
    id: 'haupteingang',
    name: 'Haupteingang',
    bereich: 'eingang',
    mapX: 90.3, mapY: 81.6,
    dauer: 5,
    planNr: '1',
    tiere: [],
    beschreibung:
      'Das große Eingangsportal mit den steinernen Tieren ist seit 1907 das Gesicht des Tierparks. Hier bekommst du den aktuellen Parkplan und die Tafel mit den Fütterungszeiten des Tages - ein Foto davon lohnt sich, denn Zeiten können tagesaktuell abweichen.',
    tipp: 'Direkt hinter dem Eingang teilt sich der Weg. Fast alle Rundwege funktionieren in beide Richtungen - gegen den Uhrzeigersinn ist es morgens meist ruhiger.',
  },
  {
    id: 'flamingoteich',
    name: 'Flamingoteich',
    bereich: 'afrika',
    mapX: 45.1, mapY: 27.2,
    dauer: 10,
    planNr: '55',
    tiere: ['flamingo', 'tamarin'],
    beschreibung:
      'Gleich hinter dem Eingang liegt einer der großen Teiche. Wasservögel und Flamingos stehen hier oft dicht am Weg - ein guter erster Halt, um anzukommen.',
    tipp: 'Für Fotos: morgens steht die Sonne günstig im Rücken des Betrachters.',
  },
  {
    id: 'elefanten',
    name: 'Elefanten-Freianlage',
    bereich: 'asien',
    mapX: 82.8, mapY: 62.2,
    dauer: 25,
    planNr: '7',
    tiere: ['elefant'],
    beschreibung:
      'Die Elefantenanlage gehört zu den bekanntesten Ecken des Parks. Hagenbeck hält Asiatische Elefanten und hat eine lange Zuchtgeschichte mit dieser Art. Von der Besucherseite blickt man über einen Graben in die Anlage - genau das Prinzip, für das der Park berühmt ist.',
    tipp: 'Wenn Nachwuchs da ist, sind die Jungtiere meist vormittags am aktivsten. Am Elefantenhaus hängen die Zeiten für die Vorführungen aus.',
  },
  {
    id: 'orangutans',
    name: 'Menschenaffen-Haus',
    bereich: 'asien',
    mapX: 92.2, mapY: 41.3,
    dauer: 20,
    planNr: '70',
    tiere: ['orangutan', 'zwergotter', 'riesenschildkroete'],
    innen: true,
    beschreibung:
      'Ein Haus mit Innen- und Aussenbereich für die Menschenaffen. Drinnen bist du sehr nah dran - und trocken, wenn es regnet.',
    tipp: 'Ruhig bleiben und ein paar Minuten stehen: Orang-Utans reagieren auf Beobachter und werden neugierig, wenn es leise ist.',
  },
  {
    id: 'tiger',
    name: 'Tigeranlage',
    bereich: 'asien',
    mapX: 87.7, mapY: 8.1,
    dauer: 15,
    planNr: '66',
    tiere: ['tiger', 'leopard', 'wapiti', 'schneeeule'],
    beschreibung:
      'Eine weitläufige Anlage mit Wasserbecken und erhöhten Liegeplätzen. Tiger sind Einzelgänger und schlafen tagsüber viel - Geduld wird hier oft belohnt.',
    tipp: 'Am späten Nachmittag, kurz vor der Fütterung, sind Grosskatzen deutlich aktiver als mittags.',
  },
  {
    id: 'loewen',
    name: 'Löwen-Freianlage',
    bereich: 'afrika',
    mapX: 33.9, mapY: 59.4,
    dauer: 15,
    tiere: ['loewe', 'mandrill', 'riesenkaenguru', 'serval', 'stachelschwein'],
    beschreibung:
      'Eine gitterlose Freianlage nach Hagenbeck-Prinzip: Ein breiter Graben trennt Besucher und Tiere, sodass der Blick frei über die Anlage geht.',
    tipp: 'Löwen ruhen bis zu 20 Stunden am Tag. Wer Bewegung sehen will, kommt früh am Morgen oder zur Fütterungszeit.',
  },
  {
    id: 'afrikapanorama',
    name: 'Afrika-Panorama',
    bereich: 'afrika',
    mapX: 26.9, mapY: 53.5,
    dauer: 25,
    planNr: '44',
    tiere: ['zebra', 'strauss', 'pinselohrschwein', 'kudu', 'maehnenspringer', 'tahr'],
    beschreibung:
      'Das große Panorama ist das Herzstück der Hagenbeck-Idee: Mehrere Tierarten stehen scheinbar in einer einzigen Landschaft hintereinander, getrennt nur durch Gräben, die man von vorn nicht sieht. Genau diese Bauweise hat Carl Hagenbeck 1896 patentieren lassen.',
    tipp: 'Stell dich mittig vor die Anlage und geh ein paar Schritte zur Seite - dann siehst du, wie die Tiefenwirkung entsteht.',
  },
  {
    id: 'strausse',
    name: 'Afrikanische Steppe',
    bereich: 'afrika',
    mapX: 28.1, mapY: 65.1,
    dauer: 10,
    tiere: ['strauss', 'zebra', 'warzenschwein'],
    planNr: '47',
    beschreibung:
      'Die große Steppenanlage teilen sich Strauße, Zebras und Warzenschweine - mehrere Arten in einer Landschaft, wie es das Hagenbeck-Prinzip vorsieht.',
    tipp: 'Ein paar Minuten bleiben: Zwischen Zebras und Straußen gibt es fast immer kleine Rangeleien um die besten Futterstellen zu sehen.',
  },
  {
    id: 'eismeer',
    name: 'Eismeer',
    bereich: 'eismeer',
    mapX: 7.3, mapY: 58.0,
    dauer: 40,
    planNr: '36-42',
    tiere: ['eisbaer', 'walross', 'pinguin', 'seebaer'],
    innen: true,
    beschreibung:
      'Das Eismeer ist die große Polaranlage des Parks und wurde 2012 eröffnet. Über Wege und Unterwasserfenster geht es an Eisbären, Walrossen, Pinguinen und Robben vorbei - teils oberhalb, teils unter der Wasserlinie.',
    tipp: 'Plane hier mehr Zeit ein als du denkst. Der Weg durch die Anlage ist länger als er von aussen aussieht, und die Unterwasserfenster sind der beste Teil.',
  },
  {
    id: 'seeloewen',
    name: 'Seebären-Becken',
    bereich: 'eismeer',
    mapX: 15.6, mapY: 55.8,
    dauer: 20,
    planNr: '37/38',
    tiere: ['seebaer', 'kranich', 'muntjak'],
    beschreibung:
      'Am Becken der Südamerikanischen Seebären gibt es täglich eine Schaufütterung mit Erklärungen der Tierpfleger. Das ist einer der wenigen festen Programmpunkte im Park - und einer der beliebtesten.',
    tipp: 'Etwa 10 Minuten vorher da sein, sonst stehst du in der dritten Reihe. Die Zeiten stehen am Eingang und in dieser App unter "Zeiten".',
    fuetterung: true,
  },
  {
    id: 'kamele',
    name: 'Kamele & Trampeltiere',
    bereich: 'asien',
    mapX: 72.1, mapY: 53.0,
    dauer: 15,
    planNr: '9',
    tiere: ['trampeltier', 'onager', 'kamtschatkabaer'],
    beschreibung:
      'Weitläufige Anlage für die zweihöckrigen Trampeltiere. In der Saison werden hier traditionell Reitrunden für Kinder angeboten - ob und wann, hängt vom Wetter und vom Tagesbetrieb ab.',
    tipp: 'Gleich nebenan wohnen die Onager und die Kamtschatkabären - beides seltene Arten, die kaum ein anderer Zoo zeigt.',
  },
  {
    id: 'alpakas',
    name: 'Riesenotter-Anlage',
    bereich: 'suedamerika',
    mapX: 58.6, mapY: 30.5,
    dauer: 15,
    planNr: '13',
    tiere: ['riesenotter', 'tapir', 'wasserschwein', 'nasenbaer'],
    beschreibung:
      'Wasseranlage der Südamerikanischen Riesenotter - der größten Otter der Welt. Die Familiengruppe ist fast immer in Bewegung und gut zu hören: Riesenotter gehören zu den gesprächigsten Raubtieren überhaupt.',
    tipp: 'Ein paar Minuten am Unterwasserfenster warten - unter Wasser zeigen die Otter, warum man sie Flusswölfe nennt.',
  },
  {
    id: 'streichelgehege',
    name: 'Streichelgehege',
    bereich: 'kinder',
    mapX: 33.0, mapY: 42.0,
    dauer: 25,
    planNr: '28',
    tiere: ['zwergziege', 'meerschweinchen', 'kaninchen'],
    beschreibung:
      'Hier dürfen Kinder rein und die Zwergziegen anfassen. Erfahrungsgemäss der Ort, an dem eine geplante Viertelstunde zu einer Dreiviertelstunde wird.',
    tipp: 'Am Ausgang gibt es Waschgelegenheiten - Händewaschen nicht vergessen. Futter nur aus dem Automaten des Parks verwenden.',
    kinder: true,
  },
  {
    id: 'spielplatz',
    name: 'Spielplatz & Wasserspiel',
    bereich: 'kinder',
    mapX: 50.5, mapY: 16.7,
    dauer: 30,
    planNr: '56',
    tiere: ['praeriebison', 'praeriehund'],
    beschreibung:
      'Großer Spielbereich mit Klettergeräten und Wasserspielstellen. Rundherum gibt es Bänke und Gastronomie - der übliche Wendepunkt eines Familienbesuchs.',
    tipp: 'Bei warmem Wetter Wechselsachen einpacken. Kinder gehen am Wasserspiel zuverlässig nass nach Hause.',
    kinder: true,
  },
  {
    id: 'japangarten',
    name: 'Japanischer Inselgarten',
    bereich: 'garten',
    mapX: 46.4, mapY: 40.2,
    dauer: 15,
    planNr: '27',
    tiere: ['pavian', 'pelikan', 'ara'],
    beschreibung:
      'Ein angelegter Garten mit Teich, Brücken und Koi-Karpfen. Keine Tierschau, sondern die ruhigste Ecke des Parks - ideal, wenn die Füße schwer werden.',
    tipp: 'Guter Ort für eine Pause zwischen zwei Parkhälften. Von hier sind Elefanten und Afrika-Panorama beide schnell erreichbar.',
    barrierearm: true,
  },
  {
    id: 'alpakawiese',
    name: 'Alpakas & Nandus',
    bereich: 'suedamerika',
    mapX: 66, mapY: 16,
    dauer: 10,
    tiere: ['alpaka', 'mara'],
    planNr: '60',
    beschreibung:
      'Wiesenanlage im Norden des Parks: Alpakas teilen sich das Gelände mit Nandus, den großen Laufvögeln Südamerikas.',
    tipp: 'Alpakas summen leise, wenn sie neugierig sind - einfach mal still hinhören.',
  },
  {
    id: 'tropenaquarium',
    name: 'Tropen-Aquarium',
    bereich: 'tropen',
    mapX: 91.5, mapY: 73.2,
    dauer: 75,
    tiere: ['hai', 'krokodil', 'rochen', 'clownfisch', 'riesenschlange', 'flughund'],
    innen: true,
    extraTicket: true,
    beschreibung:
      'Das Tropen-Aquarium ist ein eigenes Gebäude am Rand des Parks und wurde 2007 eröffnet. Auf mehreren Ebenen geht es durch Korallenriff, Regenwald, Höhle und Wüste. Achtung: Dafür wird ein eigenes Ticket beziehungsweise ein Kombiticket benötigt.',
    tipp: 'Der beste Regenschutz im ganzen Park - und deshalb bei schlechtem Wetter voll. Wer kann, geht früh oder in der letzten Stunde vor Schluss.',
  },
];

/*
 * Tiere. Die biologischen Angaben gelten für die Art allgemein.
 */
export const TIERE = [
  {
    id: 'eisbaer',
    name: 'Eisbär',
    lateinisch: 'Ursus maritimus',
    bereich: 'eismeer',
    station: 'eismeer',
    kurz: 'Größtes an Land lebendes Raubtier - und ein erstaunlich guter Schwimmer.',
    steckbrief: {
      Größe: 'bis 2,5 m Körperlänge, aufgerichtet über 3 m',
      Gewicht: 'Männchen 400-600 kg, Weibchen etwa halb so schwer',
      Alter: 'in Menschenobhut über 30 Jahre',
      Nahrung: 'vor allem Robben, dazu Fisch und Aas',
      Heimat: 'Arktis - Packeis rund um den Nordpol',
      Status: 'gefährdet (IUCN: vulnerable)',
    },
    text: [
      'Der Eisbär ist an Kälte so gut angepasst, dass Wärme sein eigentliches Problem ist. Unter dem Fell liegt eine bis zu elf Zentimeter dicke Fettschicht, die wie eine Thermoskanne wirkt.',
      'Sein Fell ist nicht weiß, sondern durchscheinend. Jedes Haar ist hohl und leitet Licht bis auf die Haut - und die ist schwarz, damit sie Wärme aufnimmt. Was wir als Weiß sehen, ist Lichtstreuung, ähnlich wie bei Schnee.',
      'Beim Schwimmen paddelt der Eisbär nur mit den Vorderbeinen, die Hinterbeine dienen als Steuer. So kann er stundenlang zwischen Eisschollen unterwegs sein.',
    ],
    wusstest: [
      'Eisbären riechen eine Robbe unter einer Schneedecke noch aus etwa einem Kilometer Entfernung.',
      'Ihre Tatzen sind so breit wie ein Essteller - das verteilt das Gewicht auf dünnem Eis.',
      'Sie halten keinen echten Winterschlaf. Nur trächtige Weibchen ziehen sich in eine Schneehöhle zurück.',
    ],
    beobachten:
      'Am Unterwasserfenster warten. Wenn ein Eisbär ins Wasser geht, sieht man von unten, wie leicht sich das schwere Tier bewegt.',
  },
  {
    id: 'walross',
    name: 'Walross',
    lateinisch: 'Odobenus rosmarus',
    bereich: 'eismeer',
    station: 'eismeer',
    kurz: 'Eine Tonne Robbe mit Stoßzähnen, Schnurrhaaren und viel Meinung.',
    steckbrief: {
      Größe: 'bis 3,5 m',
      Gewicht: 'Bullen bis über 1.200 kg',
      Alter: '30 bis 40 Jahre',
      Nahrung: 'Muscheln und andere Bodentiere',
      Heimat: 'arktische Küstengewässer',
      Status: 'Vorwarnliste (IUCN: near threatened)',
    },
    text: [
      'Walrosse suchen ihr Futter am Meeresboden, und zwar im Dunkeln und im trübem Wasser. Dabei helfen ihnen die rund 400 Schnurrhaare, mit denen sie Muscheln ertasten wie mit Fingerspitzen.',
      'Die Stoßzähne sind verlängerte Eckzähne und werden bis zu einem Meter lang. Sie dienen als Kletterhilfe beim Aufsteigen aufs Eis, als Waffe und als Rangabzeichen: Wer die längeren Zähne hat, hat in der Gruppe das Sagen.',
      'An Land wirken Walrosse unbeholfen, im Wasser sind sie wendig und können bis zu 30 Minuten tauchen.',
    ],
    wusstest: [
      'Ein Walross kann pro Mahlzeit mehrere tausend Muscheln aufnehmen - es saugt den Weichkörper heraus und lässt die Schale liegen.',
      'Die Haut der Bullen ist am Hals bis zu sechs Zentimeter dick, fast wie eine Rüstung.',
      'Bei Aufregung färbt sich die Haut rosa, weil die Blutgefässe sich weiten.',
    ],
    beobachten:
      'Wenn ein Walross direkt vor der Scheibe auftaucht, fällt die Größe erst richtig auf. Es lohnt sich, unten am Fenster zu warten statt oben am Beckenrand.',
  },
  {
    id: 'pinguin',
    name: 'Pinguine',
    lateinisch: 'Spheniscidä',
    bereich: 'eismeer',
    station: 'eismeer',
    kurz: 'Vögel, die das Fliegen aufgegeben haben - unter Wasser dafür aber perfekt sind.',
    steckbrief: {
      Größe: 'je nach Art 45 cm bis 1,2 m',
      Gewicht: '5 bis 40 kg',
      Alter: '15 bis 25 Jahre',
      Nahrung: 'Fisch, Tintenfisch, Krill',
      Heimat: 'Südhalbkugel - Antarktis, Südamerika, Afrika',
      Status: 'je nach Art unterschiedlich',
    },
    text: [
      'Pinguine sind Vögel, aber ihre Flügel sind zu starren Flossen umgebaut. Damit "fliegen" sie unter Wasser - mit bis zu 30 Stundenkilometern.',
      'Ihr Gefieder ist die dichteste Federdecke im Tierreich: bis zu 100 Federn pro Quadratzentimeter, wasserdicht eingefettet. Deshalb sieht man Pinguine so oft mit dem Schnabel im Gefieder - sie verteilen das Fett aus einer Drüse am Bürzel.',
      'Kein Pinguin lebt am Nordpol. Alle Arten leben südlich des Äquators, und ein Teil davon in durchaus warmen Regionen.',
    ],
    wusstest: [
      'Die schwarz-weiße Färbung ist Tarnung: von oben verschwindet der dunkle Rücken im Meeresgrund, von unten der helle Bauch im Gegenlicht.',
      'Pinguine erkennen ihren Partner und ihr Küken am Ruf, selbst in einer Kolonie mit tausenden Tieren.',
      'An Land wirken sie langsam, aber auf dem Bauch rutschend erreichen sie über 20 km/h.',
    ],
    beobachten:
      'Nicht nur an Land schauen. Wer sich ans Unterwasserfenster stellt, sieht den Unterschied zwischen watschelndem Vogel und Raketenschwimmer sofort.',
  },
  {
    id: 'seebaer',
    name: 'Südamerikanischer Seebär',
    lateinisch: 'Arctocephalus australis',
    bereich: 'eismeer',
    station: 'seeloewen',
    kurz: 'Die flinke Ohrenrobbe mit dem dichten Pelz - Star der Schaufütterung.',
    steckbrief: {
      Größe: 'Bullen bis 1,9 m, Weibchen deutlich kleiner',
      Gewicht: 'Bullen bis 200 kg, Weibchen um 50 kg',
      Alter: '20 bis 30 Jahre',
      Nahrung: 'Fisch, Tintenfisch, Krebstiere',
      Heimat: 'Küsten Südamerikas - Pazifik und Atlantik',
      Status: 'nicht gefährdet (IUCN: least concern)',
    },
    text: [
      'Seebären gehören wie die Seelöwen zu den Ohrenrobben: Sie haben kleine sichtbare Ohrmuscheln und können ihre Hinterflossen nach vorn klappen. Deshalb laufen sie an Land erstaunlich flink auf allen vieren.',
      'Ihren Namen verdanken sie dem Fell. Anders als Seelöwen tragen Seebären einen dichten, zweischichtigen Pelz mit wärmender Unterwolle - die aufgestellte, bräunliche Mähne der Bullen erinnerte Seefahrer an einen Bären.',
      'Bei der Schaufütterung geht es nicht um Kunststücke um ihrer selbst willen. Die Übungen sind medizinisches Training: Die Tiere lernen freiwillig, das Maul zu öffnen, eine Flosse zu zeigen oder auf die Waage zu gehen, damit Untersuchungen ohne Narkose möglich sind.',
      'Vor der Küste jagen Seebären vor allem nachts und tauchen dabei meist in den oberen Wasserschichten - Tauchgänge von zwei bis drei Minuten sind ihr Standard.',
    ],
    wusstest: [
      'Der dichte Pelz war fast ihr Verhängnis: Wegen des Fells wurden Seebären jahrhundertelang stark bejagt.',
      'Ein Seebär erkennt seinen Pfleger auf Entfernung an der Stimme.',
      'Unter Wasser steuern sie mit den Hinterflossen und rudern mit den Vorderflossen - wie Pinguine im Grossformat.',
    ],
    beobachten:
      'Zehn Minuten vor der Fütterung dasein und einen Platz seitlich zur Sonne suchen, sonst blendet das Wasser auf allen Fotos.',
  },
  {
    id: 'elefant',
    name: 'Asiatischer Elefant',
    lateinisch: 'Elephas maximus',
    bereich: 'asien',
    station: 'elefanten',
    kurz: 'Kleinere Ohren, runder Rücken - und ein Rüssel mit 40.000 Muskeln.',
    steckbrief: {
      Größe: 'Schulterhöhe bis 3 m',
      Gewicht: '3 bis 5 t',
      Alter: '60 bis 70 Jahre',
      Nahrung: 'Gräser, Blätter, Rinde, Früchte - bis 150 kg am Tag',
      Heimat: 'Süd- und Südostasien',
      Status: 'stark gefährdet (IUCN: endangered)',
    },
    text: [
      'Asiatische Elefanten unterscheiden sich vom afrikanischen Verwandten durch deutlich kleinere Ohren, einen gewölbten Rücken und einen Rüssel mit nur einem "Finger" an der Spitze statt zweien.',
      'Der Rüssel ist Nase, Hand, Trinkhalm und Werkzeug in einem. Er hat keinen einzigen Knochen, dafür zehntausende Muskelbündel - fein genug, um eine einzelne Erdnuss aufzuheben, stark genug für einen Baumstamm.',
      'Elefanten leben in Familienverbänden aus Kühen und Jungtieren, geführt von der ältesten Kuh. Bullen ziehen als Halbwüchsige weg und leben allein oder in losen Gruppen.',
      'Sie verständigen sich zu einem großen Teil in Infraschall - Tönen so tief, dass Menschen sie nicht hören, die aber über Kilometer reichen.',
    ],
    wusstest: [
      'Elefanten trinken nicht durch den Rüssel. Sie saugen Wasser an und spritzen es sich ins Maul.',
      'Die großen Ohren dienen der Kühlung: Durch die dünne Haut fließt viel Blut, das dabei Wärme abgibt.',
      'Ein Elefant erkennt sich im Spiegel selbst - das können außer ihm nur wenige Tierarten.',
      'Sie "hören" mit den Füßen: Erschütterungen im Boden nehmen sie über die Sohlen wahr.',
    ],
    beobachten:
      'Schau auf die Rückenlinie und die Ohren - danach erkennst du sofort, ob ein Elefant aus Asien oder Afrika stammt.',
  },
  {
    id: 'orangutan',
    name: 'Orang-Utan',
    lateinisch: 'Pongo',
    bereich: 'asien',
    station: 'orangutans',
    kurz: 'Der "Waldmensch" - ein Menschenaffe, der fast sein ganzes Leben in Bäumen verbringt.',
    steckbrief: {
      Größe: 'bis 1,4 m, Armspannweite bis 2,3 m',
      Gewicht: 'Männchen bis 90 kg, Weibchen etwa halb so schwer',
      Alter: 'in Menschenobhut über 50 Jahre',
      Nahrung: 'überwiegend Früchte, dazu Blätter, Rinde, Insekten',
      Heimat: 'Regenwälder auf Borneo und Sumatra',
      Status: 'vom Aussterben bedroht (IUCN: critically endangered)',
    },
    text: [
      'Der Name kommt aus dem Malaiischen: orang hutan heißt "Waldmensch". Orang-Utans sind die größten Baumbewohner der Welt und bewegen sich bedächtig von Ast zu Ast, statt zu springen.',
      'Sie gelten als besonders erfinderisch. In freier Wildbahn nutzen sie Blätter als Regenschirm und Stöcke als Werkzeug, in Zoos öffnen sie regelmäßig Verschlüsse, die eigentlich sicher sein sollten.',
      'Ausgewachsene Männchen bilden breite Wangenwülste aus. Diese Entwicklung setzt erst ein, wenn ein Männchen in seiner Gruppe die dominante Rolle einnimmt.',
      'Die größte Bedrohung ist der Verlust des Regenwaldes, vor allem durch Palmölplantagen. Bewusster Einkauf zu Hause hat hier direkte Wirkung.',
    ],
    wusstest: [
      'Orang-Utans bauen sich jeden Abend ein neues Schlafnest aus Zweigen - rund 30.000 Nester im Leben.',
      'Jungtiere bleiben sechs bis acht Jahre bei der Mutter, länger als bei fast jedem anderen Tier außer dem Menschen.',
      'Ihr Erbgut stimmt zu etwa 97 Prozent mit unserem überein.',
    ],
    beobachten:
      'Stell dich an die Scheibe und warte still. Orang-Utans beobachten Besucher oft genauso aufmerksam wie umgekehrt.',
  },
  {
    id: 'tiger',
    name: 'Tiger',
    lateinisch: 'Panthera tigris',
    bereich: 'asien',
    station: 'tiger',
    kurz: 'Die größte Katze der Welt - und jede hat ein einmaliges Streifenmuster.',
    steckbrief: {
      Größe: 'Körperlänge bis 2,8 m mit Schwanz',
      Gewicht: 'je nach Unterart 100 bis 300 kg',
      Alter: '15 bis 20 Jahre',
      Nahrung: 'Huftiere wie Hirsche und Wildschweine',
      Heimat: 'Asien - von Sibirien bis Sumatra',
      Status: 'stark gefährdet (IUCN: endangered)',
    },
    text: [
      'Tiger sind Einzelgänger mit großen Revieren, die sie über Duftmarken und Kratzspuren markieren. Begegnungen zwischen erwachsenen Tieren sind selten und meist kurz.',
      'Das Streifenmuster ist so individuell wie ein Fingerabdruck. Forscher identifizieren einzelne Tiere in freier Wildbahn allein anhand von Fotofallenbildern.',
      'Anders als die meisten Katzen gehen Tiger gern ins Wasser. An heißen Tagen liegen sie stundenlang in Becken und Bächen.',
      'Sie jagen aus dem Anschleichen. Der eigentliche Angriff geht über wenige Meter - dafür aber mit einer Wucht, die ein Beutetier von den Beinen holt.',
    ],
    wusstest: [
      'Auch die Haut eines Tigers ist gestreift, nicht nur das Fell.',
      'Tiger können aus dem Stand mehrere Meter weit springen.',
      'Ihr Brüllen enthält Infraschallanteile, die man eher spürt als hört.',
    ],
    beobachten:
      'Such die erhöhten Plätze der Anlage ab. Tiger liegen gern oben mit Übersicht - dort sind sie am ehesten zu finden.',
  },
  {
    id: 'trampeltier',
    name: 'Trampeltier',
    lateinisch: 'Camelus ferus f. bactrianus',
    bereich: 'asien',
    station: 'kamele',
    kurz: 'Das Kamel mit zwei Höckern - gebaut für minus 30 bis plus 40 Grad.',
    steckbrief: {
      Größe: 'Schulterhöhe bis 2,3 m',
      Gewicht: '450 bis 700 kg',
      Alter: '30 bis 40 Jahre',
      Nahrung: 'harte Gräser, Sträucher, auch salzige Pflanzen',
      Heimat: 'Steppen und Wüsten Zentralasiens',
      Status: 'Wildform vom Aussterben bedroht',
    },
    text: [
      'In den Höckern steckt kein Wasser, sondern Fett. Es dient als Energiespeicher - und weil das Fett gebündelt oben sitzt statt über den ganzen Körper verteilt, kann der Rest des Körpers besser Wärme abgeben.',
      'Trampeltiere überstehen extreme Temperaturschwankungen. Im Winter wächst ein dichtes Wollkleid, das im Frühjahr in groben Fetzen abfällt - das sieht ungepflegt aus, ist aber normal.',
      'Sie können in wenigen Minuten mehr als 100 Liter Wasser trinken, ohne Schaden zu nehmen.',
    ],
    wusstest: [
      'Doppelte Wimpernreihen und verschließbare Nasenlöcher halten Sandstürme ab.',
      'Kamele sind Passgänger: Sie setzen beide Beine einer Körperseite gleichzeitig - daher der schaukelnde Gang.',
      'Ihre Fußsohlen sind breite Schwielen, die auf Sand nicht einsinken.',
    ],
    beobachten:
      'Hängende Höcker sind kein schlechtes Zeichen für die Haltung, sondern zeigen nur, wie voll der Fettspeicher gerade ist.',
  },
  {
    id: 'zebra',
    name: 'Zebra',
    lateinisch: 'Equus quagga',
    bereich: 'afrika',
    station: 'strausse',
    kurz: 'Gestreifte Wildpferde - und niemand hat zwei gleiche Muster.',
    steckbrief: {
      Größe: 'Schulterhöhe bis 1,4 m',
      Gewicht: '250 bis 400 kg',
      Alter: '20 bis 30 Jahre',
      Nahrung: 'Gräser',
      Heimat: 'Savannen Ost- und Südafrikas',
      Status: 'nicht gefährdet (IUCN: near threatened bei einigen Unterarten)',
    },
    text: [
      'Warum Zebras gestreift sind, war lange umstritten. Die derzeit beste Erklärung: Die Streifen stören stechende Fliegen, die Träger gefährlicher Krankheiten sind - sie landen auf gestreiften Flächen deutlich seltener.',
      'Zebras leben in Familiengruppen aus einem Hengst, mehreren Stuten und Fohlen. Bei Wanderungen schließen sich viele Gruppen zu großen Herden zusammen.',
      'Sie sind wehrhafter als Hauspferde. Ein Zebratritt kann einen Löwen ernsthaft verletzen, und deshalb greifen Raubtiere bevorzugt Jungtiere an.',
    ],
    wusstest: [
      'Ein Zebrafohlen erkennt seine Mutter am Streifenmuster - deshalb stellt sie sich in den ersten Tagen zwischen Fohlen und Herde.',
      'Zebras schlafen im Stehen und immer im Wechsel: Mindestens ein Tier der Gruppe hält Wache.',
      'Trotz Ähnlichkeit lassen sich Zebras nicht wie Pferde als Reittiere halten - sie sind zu schreckhaft und eigensinnig.',
    ],
    beobachten: 'Vergleiche zwei Tiere nebeneinander: Am Hals und an den Flanken sieht man die Musterunterschiede sofort.',
  },
  {
    id: 'strauss',
    name: 'Strauß',
    lateinisch: 'Struthio camelus',
    bereich: 'afrika',
    station: 'strausse',
    kurz: 'Größter Vogel der Welt - kann nicht fliegen, aber schneller rennen als ein Rennrad fährt.',
    steckbrief: {
      Größe: 'bis 2,8 m',
      Gewicht: 'bis 150 kg',
      Alter: '40 bis 50 Jahre',
      Nahrung: 'Pflanzen, Samen, Insekten',
      Heimat: 'Afrikanische Savannen und Halbwüsten',
      Status: 'nicht gefährdet (IUCN: least concern)',
    },
    text: [
      'Strauße erreichen im Sprint bis zu 70 Stundenkilometer und halten 50 km/h über längere Strecken. Möglich macht das ein Fuß mit nur zwei Zehen - eine Bauweise wie ein Laufschuh.',
      'Dass Strauße bei Gefahr den Kopf in den Sand stecken, ist ein Märchen. Sie legen bei Bedrohung Hals und Kopf flach auf den Boden, um von weitem wie ein Busch auszusehen.',
      'Ein Straußenei wiegt etwa 1,5 Kilogramm und entspricht rund 25 Hühnereiern. Die Schale ist so stabil, dass ein erwachsener Mensch darauf stehen kann.',
    ],
    wusstest: [
      'Das Auge eines Strausses ist etwa fünf Zentimeter groß - größer als sein Gehirn.',
      'Ein Tritt kann tödlich sein; die Zehe trägt eine kräftige Kralle.',
      'Männchen sind schwarz-weiß, Weibchen graubraun - so ist das Weibchen am Nest getarnt.',
    ],
    beobachten: 'Achte auf die Farbe: schwarz-weiß ist der Hahn, graubraun die Henne.',
  },
  {
    id: 'loewe',
    name: 'Löwe',
    lateinisch: 'Panthera leo',
    bereich: 'afrika',
    station: 'loewen',
    kurz: 'Die einzige Katze, die in festen Gruppen lebt - und die faulste dazu.',
    steckbrief: {
      Größe: 'Körperlänge bis 2,5 m mit Schwanz',
      Gewicht: 'Männchen bis 250 kg',
      Alter: '15 bis 20 Jahre',
      Nahrung: 'Huftiere wie Gnus, Zebras, Antilopen',
      Heimat: 'Afrika südlich der Sahara, kleiner Restbestand in Indien',
      Status: 'gefährdet (IUCN: vulnerable)',
    },
    text: [
      'Löwen leben im Rudel: mehrere verwandte Weibchen mit Jungtieren und ein bis drei Männchen. Die Weibchen jagen gemeinsam und meist in der Dämmerung.',
      'Bis zu 20 Stunden am Tag verbringen Löwen mit Ruhen. Das ist kein Zeichen von Langeweile, sondern Energiehaushalt: Jagen ist teuer, Verdauen dauert.',
      'Die Mähne des Männchens zeigt Kondition an. Dunkler und voller bedeutet meist älter und stärker - Rivalen und Weibchen lesen das auf Entfernung ab.',
      'Ein Brüllen ist bis zu acht Kilometer weit zu hören und dient der Reviermarkierung.',
    ],
    wusstest: [
      'Löwen sind die einzigen Grosskatzen mit deutlich unterschiedlichem Aussehen von Männchen und Weibchen.',
      'Sie können kurzzeitig 60 km/h laufen, halten das aber nur über wenige hundert Meter durch.',
      'Junge Löwen haben Flecken im Fell, die sich erst mit der Zeit verlieren.',
    ],
    beobachten:
      'Sieh dir den Graben vor der Anlage an - er ist das eigentliche "Gitter". Genau diese Bauweise hat Hagenbeck berühmt gemacht.',
  },
  {
    id: 'flamingo',
    name: 'Flamingo',
    lateinisch: 'Phoenicopterus',
    bereich: 'afrika',
    station: 'flamingoteich',
    kurz: 'Rosa wird man hier nicht geboren - man frisst sich rosa.',
    steckbrief: {
      Größe: '1,2 bis 1,5 m',
      Gewicht: '2 bis 4 kg',
      Alter: 'oft über 30 Jahre',
      Nahrung: 'Kleinkrebse, Algen, Insektenlarven',
      Heimat: 'Salzseen und Lagunen in Afrika, Asien, Amerika, Südeuropa',
      Status: 'nicht gefährdet (IUCN: least concern)',
    },
    text: [
      'Die rosa Farbe stammt aus der Nahrung. Kleinkrebse und Algen enthalten Carotinoide, die sich im Gefieder einlagern. Ohne diese Stoffe würden Flamingos weiß bleiben.',
      'Flamingos fressen mit dem Kopf verkehrt herum im Wasser. Der Schnabel arbeitet wie ein Sieb: Wasser wird angesaugt und durch feine Lamellen wieder herausgedrückt, die Nahrung bleibt hängen.',
      'Das Stehen auf einem Bein spart Wärme. Im kühlen Wasser verliert ein eingezogenes Bein keine Körperwärme - und die Haltung kostet die Vögel praktisch keine Kraft.',
    ],
    wusstest: [
      'Flamingos bruüten auf kegelförmigen Schlammhügeln, die sie selbst aufbauen.',
      'Beide Eltern füttern das Küken mit einer rötlichen "Kropfmilch".',
      'In Kolonien führen sie gemeinsame Balzparaden auf - hunderte Vögel drehen gleichzeitig die Köpfe.',
    ],
    beobachten: 'Sieh dir das Gefieder verschiedener Tiere an - je kräftiger das Rosa, desto besser die Nährstoffversorgung.',
  },
  {
    id: 'riesenotter',
    name: 'Riesenotter',
    lateinisch: 'Pteronura brasiliensis',
    bereich: 'suedamerika',
    station: 'alpakas',
    kurz: 'Der größte Otter der Welt - lebt in Familie und redet fast ohne Pause.',
    steckbrief: {
      Größe: 'bis 1,8 m mit Schwanz',
      Gewicht: '22 bis 32 kg',
      Alter: '10 bis 15 Jahre, in Menschenobhut länger',
      Nahrung: 'vor allem Fisch, dazu Krebse',
      Heimat: 'Flüsse des Amazonas- und Orinoco-Gebiets',
      Status: 'stark gefährdet (IUCN: endangered)',
    },
    text: [
      'Riesenotter leben in Familiengruppen aus einem Elternpaar und dem Nachwuchs mehrerer Jahre. Gejagt wird gemeinsam - eine Gruppe treibt Fischschwärme zusammen wie ein Rudel Wölfe, daher der südamerikanische Name "Flusswolf".',
      'Sie sind ausgesprochen gesprächig: Forscher unterscheiden mehr als 20 verschiedene Rufe, vom Bettel-Quieken der Jungen bis zum Alarmschnauben. Auch an der Anlage ist fast immer etwas zu hören.',
      'Jeder Riesenotter trägt an der Kehle eine helle, unregelmäßige Zeichnung - so individuell wie ein Fingerabdruck. Beim Aufrichten im Wasser zeigen sich die Tiere gegenseitig ihre Kehlflecken.',
      'In Südamerika sind Riesenotter durch Jagd, Goldwäsche und Lebensraumverlust selten geworden; Zoos koordinieren die Zucht in einem europäischen Erhaltungsprogramm.',
    ],
    wusstest: [
      'Der abgeflachte Schwanz wirkt wie ein Paddel - im Sprint schwimmt ein Riesenotter schneller, als ein Mensch laufen kann.',
      'Riesenotter fressen täglich etwa drei bis vier Kilogramm Fisch - gehalten wird die Beute mit den Vorderpfoten wie mit Händen.',
      'Zum Schlafen und für die Jungen gräbt die Familie Höhlen in die Uferböschung.',
    ],
    beobachten:
      'Auf die Kehlflecken achten: Damit lassen sich die einzelnen Familienmitglieder auseinanderhalten.',
  },
  {
    id: 'alpaka',
    name: 'Alpaka',
    lateinisch: 'Vicugna pacos',
    bereich: 'suedamerika',
    station: 'alpakawiese',
    kurz: 'Kleinkamel aus den Anden - seit über 5.000 Jahren wegen der Wolle gehalten.',
    steckbrief: {
      Größe: 'Schulterhöhe etwa 1 m',
      Gewicht: '55 bis 75 kg',
      Alter: '15 bis 20 Jahre',
      Nahrung: 'Gräser und Kräuter',
      Heimat: 'Hochanden in Peru, Bolivien, Chile',
      Status: 'Haustierform, nicht gefährdet',
    },
    text: [
      'Alpakas sind Kamele ohne Höcker. Sie stammen vom wilden Vikunja ab und wurden von den Andenvölkern über Jahrtausende auf Wollqualität gezüchtet.',
      'Ihre Wolle ist wärmer als Schafwolle und enthält kein Wollfett, deshalb reagieren viele Menschen mit Wollallergie darauf nicht.',
      'In der Gruppe klären sie Rangfragen mit Halsringen, Spucken und Drohblicken - für Menschen ist das Spucken selten ein Thema.',
      'Alpakas nutzen gemeinsame Kotplätze. Das hält die Weide sauber und begrenzt Parasiten.',
    ],
    wusstest: [
      'Alpakas summen leise, wenn sie unsicher oder neugierig sind.',
      'Ein Tier liefert pro Schur etwa drei Kilogramm Wolle.',
      'Sie haben gespaltene Sohlen mit Schwielen statt Hufen und schädigen die Grasnarbe kaum.',
    ],
    beobachten: 'Ohrenstellung beachten: nach vorn heißt interessiert, flach angelegt heißt genervt.',
  },
  {
    id: 'zwergziege',
    name: 'Zwergziege',
    lateinisch: 'Capra hircus',
    bereich: 'kinder',
    station: 'streichelgehege',
    kurz: 'Klein, frech, kletterfreudig - das Tier zum Anfassen.',
    steckbrief: {
      Größe: 'Schulterhöhe 40 bis 60 cm',
      Gewicht: '20 bis 35 kg',
      Alter: '12 bis 15 Jahre',
      Nahrung: 'Heu, Laub, Kräuter',
      Heimat: 'Haustierform, ursprünglich Westafrika',
      Status: 'Haustierrasse',
    },
    text: [
      'Zwergziegen sind neugierig und kontaktfreudig - genau deshalb stehen sie im Streichelgehege. Sie klettern gern auf alles, was höher ist als sie selbst.',
      'Ihre waagerechten, rechteckigen Pupillen geben ein sehr breites Blickfeld von fast 320 Grad. Eine Ziege sieht dich also auch dann, wenn sie scheinbar wegschaut.',
      'Ziegen sind keine Allesfresser. Papier, Plastik und mitgebrachtes Brot machen sie krank - Futter nur aus den Automaten des Parks.',
    ],
    wusstest: [
      'Ziegen erkennen die Gesichter vertrauter Menschen und bevorzugen freundliche Mienen.',
      'Sie haben keine oberen Schneidezähne, sondern eine harte Kauplatte.',
      'Die Ziege war eines der ersten Nutztiere des Menschen - domestiziert vor rund 10.000 Jahren.',
    ],
    beobachten: 'Streicheln am Hals und an der Schulter, nicht am Kopf - Hörner sind kein Griff.',
    kinder: true,
  },
  {
    id: 'hai',
    name: 'Riffhaie',
    lateinisch: 'Carcharhinidä',
    bereich: 'tropen',
    station: 'tropenaquarium',
    kurz: 'Perfekt gebaute Jäger - und deutlich harmloser als ihr Ruf.',
    steckbrief: {
      Größe: 'je nach Art 1,5 bis 2 m',
      Gewicht: '20 bis 50 kg',
      Alter: '20 bis 25 Jahre',
      Nahrung: 'Fisch, Tintenfisch, Krebse',
      Heimat: 'tropische Korallenriffe',
      Status: 'mehrere Arten gefährdet',
    },
    text: [
      'Haie sind älter als Bäume: Ihre Bauform existiert seit über 400 Millionen Jahren. Ihr Skelett besteht nicht aus Knochen, sondern aus Knorpel - leichter und biegsamer.',
      'Sie besitzen ein zusätzliches Sinnesorgan, die Lorenzinischen Ampullen. Damit nehmen sie schwächste elektrische Felder wahr, wie sie jeder Muskel erzeugt. Ein Hai findet Beute damit selbst im Sand.',
      'Haizähne stehen in mehreren Reihen. Fällt einer aus, rückt der nächste nach - im Lauf eines Lebens sind das tausende.',
      'Weltweit gibt es pro Jahr eine sehr geringe zweistellige Zahl an Haiunfällen - während der Mensch jährlich zig Millionen Haie tötet.',
    ],
    wusstest: [
      'Haihaut fühlt sich wie Schmirgelpapier an: Sie besteht aus winzigen Zähnchen, die den Wasserwiderstand senken.',
      'Viele Haie müssen schwimmen, um Wasser über die Kiemen zu bekommen.',
      'Ihr Geruchssinn erkennt Blut in extremer Verdünnung - allerdings nicht "kilometerweit", wie oft behauptet.',
    ],
    beobachten:
      'Im großen Becken lohnt sich, einen Hai zwei, drei Runden zu verfolgen. Der Weg wiederholt sich - Haie schwimmen bevorzugte Bahnen.',
  },
  {
    id: 'krokodil',
    name: 'Krokodile',
    lateinisch: 'Crocodylia',
    bereich: 'tropen',
    station: 'tropenaquarium',
    kurz: 'Lebende Fossilien mit dem stärksten Biss der Tierwelt.',
    steckbrief: {
      Größe: 'je nach Art 2 bis 6 m',
      Gewicht: 'bis über 1.000 kg',
      Alter: '50 bis 80 Jahre',
      Nahrung: 'Fisch, Vögel, Säugetiere',
      Heimat: 'Tropen und Subtropen weltweit',
      Status: 'je nach Art unterschiedlich',
    },
    text: [
      'Krokodile gibt es seit rund 200 Millionen Jahren in nahezu unveränderter Bauform. Sie sind näher mit Vögeln verwandt als mit Echsen.',
      'Der Biss eines großen Krokodils ist der stärkste gemessene im Tierreich. Die Muskeln zum Öffnen des Mauls sind dagegen schwach - ein Grund, warum ein umwickeltes Maul sicher zu ist.',
      'Sie sind wechselwarm und regeln ihre Temperatur durch Ortswechsel: Sonne zum Aufwärmen, Wasser oder Schatten zum Abkühlen. Deshalb liegen sie stundenlang bewegungslos.',
      'Krokodilmütter bewachen ihr Gelege und tragen die frisch geschlüpften Jungen im Maul zum Wasser - ausgesprochene Brutpflege für ein Reptil.',
    ],
    wusstest: [
      'Ob aus einem Ei ein Männchen oder Weibchen wird, entscheidet die Bruttemperatur.',
      'Ein Krokodil kann seinen Stoffwechsel so weit herunterfahren, dass es monatelang ohne Nahrung auskommt.',
      'Die Schuppen tragen Drucksensoren, mit denen kleinste Wellenbewegungen wahrgenommen werden.',
    ],
    beobachten: 'Achte auf die Augen: Auch scheinbar schlafende Krokodile verfolgen Bewegungen vor der Scheibe.',
  },
  {
    id: 'rochen',
    name: 'Rochen',
    lateinisch: 'Batoidea',
    bereich: 'tropen',
    station: 'tropenaquarium',
    kurz: 'Flach gebaute Verwandte der Haie, die über den Boden "fliegen".',
    steckbrief: {
      Größe: 'je nach Art 40 cm bis mehrere Meter Spannweite',
      Gewicht: 'stark artabhängig',
      Alter: '15 bis 25 Jahre',
      Nahrung: 'Muscheln, Krebse, kleine Fische',
      Heimat: 'Meere weltweit, einige Arten in Flüssen',
      Status: 'viele Arten gefährdet',
    },
    text: [
      'Rochen sind Knorpelfische und damit enge Verwandte der Haie - im Grunde flachgedrückte Haie mit stark vergrösserten Brustflossen.',
      'Maul und Kiemen liegen auf der Unterseite. Damit beim Liegen im Sand kein Sand eingesogen wird, atmen Rochen über zwei Öffnungen oben am Kopf, die Spritzlöcher.',
      'Was auf der Unterseite wie ein lächelndes Gesicht aussieht, ist das Maul mit den Nasengruben - Augen sitzen oben.',
    ],
    wusstest: [
      'Manche Rochenarten erzeugen Stromstösse zur Verteidigung.',
      'Ihr Stachel ist eine Verteidigungswaffe, kein Jagdwerkzeug.',
      'Rochen können mehrere Jahrzehnte alt werden und vermehren sich sehr langsam - deshalb sind sie durch Fischerei stark gefährdet.',
    ],
    beobachten: 'Vom Beckenrand aus von oben schauen: Der Wellenschlag der Flossenränder ist von dort am besten zu sehen.',
  },
  {
    id: 'clownfisch',
    name: 'Clownfisch & Korallenriff',
    lateinisch: 'Amphiprion',
    bereich: 'tropen',
    station: 'tropenaquarium',
    kurz: 'Der Fisch, der in einer giftigen Anemone wohnt - und dabei alle Weibchen stellt.',
    steckbrief: {
      Größe: '7 bis 12 cm',
      Gewicht: 'wenige Gramm',
      Alter: '6 bis 10 Jahre',
      Nahrung: 'Plankton, Algen, Futterreste der Anemone',
      Heimat: 'Korallenriffe im Indopazifik',
      Status: 'nicht gefährdet',
    },
    text: [
      'Clownfische leben in Seeanemonen, deren Nesselzellen für andere Fische gefährlich sind. Eine Schleimschicht schützt sie - und sie gewöhnen die Anemone langsam an sich, indem sie sie anfangs nur kurz berühren.',
      'Alle Clownfische werden als Männchen geboren. Stirbt das dominante Weibchen einer Gruppe, wandelt sich das ranghöchste Männchen in ein Weibchen um.',
      'Das Korallenriff selbst ist ein Tier-Bauwerk: Winzige Polypen bauen über Jahrtausende Kalkskelette. Ihre Farbe stammt von Algen, die in ihnen leben - stoßen sie diese bei zu warmem Wasser ab, bleicht das Riff aus.',
    ],
    wusstest: [
      'Ein Clownfischpaar verteidigt seine Anemone gegen deutlich größere Fische.',
      'Riffe bedecken weniger als ein Prozent des Meeresbodens, beherbergen aber rund ein Viertel aller Meeresarten.',
      'Korallen fressen nachts - dann strecken sie ihre Tentakel aus.',
    ],
    beobachten:
      'Vor dem Riffbecken einfach mal zwei Minuten stehenbleiben und nur eine Anemone beobachten. Es passiert mehr, als man auf den ersten Blick sieht.',
  },
  {
    id: 'riesenschlange',
    name: 'Riesenschlangen',
    lateinisch: 'Boidä & Pythonidä',
    bereich: 'tropen',
    station: 'tropenaquarium',
    kurz: 'Kein Gift, dafür Muskeln - und ein Kiefer, der sich aushängen lässt.',
    steckbrief: {
      Größe: 'je nach Art 3 bis 8 m',
      Gewicht: 'bis über 100 kg',
      Alter: '20 bis 30 Jahre',
      Nahrung: 'Säugetiere und Vögel',
      Heimat: 'Tropen Afrikas, Asiens und Südamerikas',
      Status: 'je nach Art unterschiedlich',
    },
    text: [
      'Riesenschlangen sind Würger. Sie halten die Beute mit den Zähnen fest und legen Körperschlingen darum. Mit jedem Ausatmen des Beutetiers ziehen sie enger - der Kreislauf bricht schneller zusammen, als früher angenommen wurde.',
      'Ihr Unterkiefer ist nicht starr mit dem Schädel verbunden und in der Mitte nur durch ein dehnbares Band verbunden. Deshalb können sie Beute verschlingen, die dicker ist als sie selbst.',
      'Nach einer großen Mahlzeit verdauen sie wochenlang und bewegen sich kaum. Manche Arten fressen nur wenige Male im Jahr.',
      'Viele Arten besitzen Grubenorgane an den Lippen, mit denen sie Wärmebilder ihrer Umgebung wahrnehmen - sie "sehen" warme Beute im Dunkeln.',
    ],
    wusstest: [
      'Schlangen haben keine Augenlider. Über dem Auge liegt eine durchsichtige Schuppe, die bei der Häutung mit abgeht.',
      'Sie riechen mit der Zunge: Die gespaltene Spitze bringt Duftteilchen an ein Sinnesorgan im Gaumen.',
      'Anakondas sind die schwersten, Netzpythons die längsten Schlangen der Welt.',
    ],
    beobachten: 'Such nach der abgestreiften Haut im Terrarium - daran lässt sich die Größe gut abschätzen.',
  },
  {
    id: 'flughund',
    name: 'Flughunde',
    lateinisch: 'Pteropodidä',
    bereich: 'tropen',
    station: 'tropenaquarium',
    kurz: 'Fliegende Säugetiere, die kopfüber schlafen und Früchte lieben.',
    steckbrief: {
      Größe: 'Spannweite bis 1,5 m bei großen Arten',
      Gewicht: '100 g bis 1,5 kg',
      Alter: '15 bis 30 Jahre',
      Nahrung: 'Früchte und Nektar',
      Heimat: 'Tropen Afrikas, Asiens und Australiens',
      Status: 'einige Arten gefährdet',
    },
    text: [
      'Flughunde sind die einzigen Säugetiere, die aktiv fliegen können - ihre Flügel sind Hautspannen zwischen stark verlängerten Fingern.',
      'Anders als die meisten Fledermäuse orientieren sich Flughunde überwiegend mit Augen und Nase statt per Echoortung. Ihre Sicht ist bei Dämmerung ausgezeichnet.',
      'Sie sind wichtige Bestäuber und Samenverbreiter. Viele tropische Bäume - darunter Durian und wilde Bananen - hängen von ihnen ab.',
      'Kopfüber zu hängen kostet sie keine Kraft: Die Krallen halten durch das eigene Körpergewicht, ein Sperrmechanismus in den Sehnen macht es möglich.',
    ],
    wusstest: [
      'Beim Hangeln benutzen sie die Daumenkrallen wie Haken.',
      'Ein Flughund kann in einer Nacht mehr als sein eigenes Körpergewicht an Früchten verwerten.',
      'Ihr Flugbild ist deutlich ruhiger und gleitender als das kleiner Fledermäuse.',
    ],
    beobachten:
      'In der Dämmerungsabteilung erst ein bis zwei Minuten stehenbleiben, bis sich die Augen anpassen - dann sieht man deutlich mehr.',
  },
  {
    id: 'kamtschatkabaer',
    name: 'Kamtschatkabär',
    lateinisch: 'Ursus arctos beringianus',
    bereich: 'asien',
    station: 'kamele',
    kurz: 'Einer der größten Braunbären der Welt - Lachsfänger aus dem fernen Osten Russlands.',
    steckbrief: {
      Größe: 'aufgerichtet bis 3 m',
      Gewicht: 'Männchen bis 650 kg',
      Alter: '25 bis 35 Jahre',
      Nahrung: 'Allesfresser - Fisch, Beeren, Kräuter, Aas',
      Heimat: 'Halbinsel Kamtschatka, Russland',
      Status: 'Unterart nicht bedroht, streng geschützt',
    },
    text: [
      'Der Kamtschatkabär ist eine der größten Unterarten des Braunbären - nur der Kodiakbär wird noch schwerer. Auf der Halbinsel Kamtschatka lebt die dichteste Braunbären-Population der Erde.',
      'Sein Speiseplan hängt an der Jahreszeit: Im Sommer stehen die Bären an den Flüssen und fangen wandernde Lachse, im Herbst fressen sie sich an Beeren einen Winterspeck von weit über 100 Kilogramm an.',
      'Den Winter verbringen Braunbären in einer Winterruhe - kein echter Winterschlaf, denn die Körpertemperatur sinkt nur wenig und die Tiere sind leicht zu wecken.',
    ],
    wusstest: [
      'Trotz seiner Masse sprintet ein Braunbär kurzzeitig über 50 km/h.',
      'Bären sehen mässig, riechen aber besser als jeder Spürhund.',
      'Hagenbeck zeigt Kamtschatkabären als einer von sehr wenigen Zoos in Europa.',
    ],
    beobachten:
      'Fütterungszeiten beachten - beim Fressen zeigen die Bären, wie geschickt ihre großen Pranken sind.',
  },
  {
    id: 'leopard',
    name: 'Nordchinesischer Leopard',
    lateinisch: 'Panthera pardus japonensis',
    bereich: 'asien',
    station: 'tiger',
    kurz: 'Eine der seltensten Grosskatzen der Welt - und ein Meister im Klettern.',
    steckbrief: {
      Größe: 'Körperlänge bis 1,9 m mit Schwanz',
      Gewicht: '35 bis 75 kg',
      Alter: '15 bis 20 Jahre',
      Nahrung: 'Hirsche, Wildschweine, kleinere Säugetiere',
      Heimat: 'Bergwälder Nordchinas',
      Status: 'Unterart stark bedroht, in Zoos sehr selten',
    },
    text: [
      'Der Nordchinesische Leopard trägt ein besonders kräftig gefärbtes Fell mit großen, dunkel geränderten Rosetten. In freier Wildbahn gibt es nur noch wenige hundert Tiere, und auch in Zoos ist die Unterart eine Rarität.',
      'Leoparden sind die besten Kletterer unter den Grosskatzen. Ihre Beute ziehen sie in freier Wildbahn auf Bäume, um sie vor Konkurrenten in Sicherheit zu bringen - ein erwachsener Leopard stemmt dabei mehr als sein eigenes Körpergewicht senkrecht nach oben.',
      'Wie alle Leoparden sind sie Einzelgänger und vor allem in der Dämmerung aktiv. Tagsüber ruhen sie gern erhöht mit Überblick.',
    ],
    wusstest: [
      'Jede Rosette im Fell ist einmalig - wie beim Tiger die Streifen.',
      'Leoparden springen aus dem Stand über drei Meter hoch.',
      'Das europäische Zuchtprogramm für diese Unterart umfasst nur eine Handvoll Zoos - Hagenbeck gehört dazu.',
    ],
    beobachten:
      'Zuerst die erhöhten Plattformen und Bäume absuchen - Leoparden liegen fast immer oben.',
  },
  {
    id: 'praeriebison',
    name: 'Präriebison',
    lateinisch: 'Bison bison bison',
    bereich: 'amerika',
    station: 'spielplatz',
    kurz: 'Das schwerste Landtier Nordamerikas - und eine Rettungsgeschichte.',
    steckbrief: {
      Größe: 'Schulterhöhe bis 1,9 m',
      Gewicht: 'Bullen bis 900 kg',
      Alter: '15 bis 25 Jahre',
      Nahrung: 'Gräser',
      Heimat: 'Prairien Nordamerikas',
      Status: 'Bestand stabil, aber auf Schutzgebiete beschränkt',
    },
    text: [
      'Einst zogen zig Millionen Bisons durch die nordamerikanischen Prairien. Ende des 19. Jahrhunderts waren nach der Bejagung weniger als tausend Tiere übrig - erst Schutzprogramme, auch mit Zoo-Tieren, retteten die Art.',
      'Der mächtige Buckel besteht aus Muskeln, die den riesigen Kopf tragen. Im Winter schiebt ein Bison damit den Schnee beiseite, um an das Gras darunter zu kommen.',
      'Trotz ihrer Masse sind Bisons erstaunlich beweglich: Sie erreichen im Galopp über 50 km/h und springen aus dem Stand höher, als ein Weidezaun misst.',
    ],
    wusstest: [
      'Das dichte Winterfell isoliert so gut, dass Schnee auf dem Rücken liegen bleibt, ohne zu schmelzen.',
      'Bisons wälzen sich in Staubmulden - das pflegt das Fell und vertreibt Insekten.',
      'Kälber kommen rotbraun zur Welt und färben sich erst nach Monaten dunkel.',
    ],
    beobachten:
      'Im Frühsommer verlieren Bisons ihr Winterfell in großen Fetzen - das sieht wild aus, ist aber völlig normal.',
  },
  {
    id: 'mandrill',
    name: 'Mandrill',
    lateinisch: 'Mandrillus sphinx',
    bereich: 'afrika',
    station: 'loewen',
    kurz: 'Der bunteste Affe der Welt - je kräftiger die Farben, desto höher der Rang.',
    steckbrief: {
      Größe: 'Männchen bis 80 cm Körperlänge',
      Gewicht: 'Männchen bis 35 kg, Weibchen etwa halb so schwer',
      Alter: '20 bis 30 Jahre',
      Nahrung: 'Früchte, Samen, Insekten, kleine Wirbeltiere',
      Heimat: 'Regenwälder Zentralafrikas',
      Status: 'gefährdet (IUCN: vulnerable)',
    },
    text: [
      'Mandrille sind die größten Affen außerhalb der Menschenaffen - und die farbenprächtigsten Säugetiere überhaupt: Die Männchen tragen leuchtend blaue Wülste und eine rote Nase, dazu ein gelbes Backenbart-Feld.',
      'Die Farben sind ein Rangabzeichen. Je kräftiger Blau und Rot leuchten, desto höher steht das Männchen in der Gruppe - verliert es Kämpfe, verblassen die Farben messbar.',
      'In den Wäldern Zentralafrikas ziehen Mandrille in Horden umher, die zeitweise mehrere hundert Tiere umfassen - die größten bekannten Affenverbände der Welt.',
    ],
    wusstest: [
      'In den dehnbaren Backentaschen trägt ein Mandrill einen Vorrat davon, was er unterwegs findet.',
      'Das Gähnen mit weit geöffnetem Maul ist eine Drohung - dabei zeigen die Männchen ihre bis zu 6 cm langen Eckzähne.',
      'Mandrille verständigen sich auch über Mimik und leise Grunzlaute - dauerhaft laut sind sie nur bei Streit.',
    ],
    beobachten:
      'Auf die Gesichter achten: Ranghohe Männchen erkennst du sofort an den leuchtenden Farben.',
  },
  {
    id: 'riesenkaenguru',
    name: 'Rotes Riesenkänguru',
    lateinisch: 'Osphranter rufus',
    bereich: 'australien',
    station: 'loewen',
    kurz: 'Das größte Beuteltier der Welt - springt weiter als ein Auto lang ist.',
    steckbrief: {
      Größe: 'aufgerichtet bis 1,8 m',
      Gewicht: 'Männchen bis 90 kg',
      Alter: '15 bis 20 Jahre',
      Nahrung: 'Gräser und Kräuter',
      Heimat: 'Trockengebiete Australiens',
      Status: 'nicht gefährdet (IUCN: least concern)',
    },
    text: [
      'Rote Riesenkängurus sind die größten Beuteltiere der Erde. Ein flüchtendes Tier schafft Sprünge von über neun Metern Weite und hält dabei 50 km/h - der dicke Schwanz dient als Gegengewicht und Stütze.',
      'Das Junge kommt nach nur einem Monat Tragzeit winzig zur Welt - nackt, blind und kaum so groß wie ein Gummibärchen. Es klettert selbstständig in den Beutel und wächst dort viele Monate weiter.',
      'Kängurus können ein befruchtetes Ei in Wartestellung halten: Erst wenn der Beutel frei wird, entwickelt es sich weiter. So passt sich der Nachwuchs an Dürrezeiten an.',
      'Männchen klären Rangfragen im "Boxkampf": Sie stützen sich auf den Schwanz und treten mit beiden Hinterbeinen gleichzeitig zu.',
    ],
    wusstest: [
      'Rückwärts gehen können Kängurus nicht - ihr Körperbau lässt es nicht zu.',
      'Beim Hüpfen sparen Kängurus Energie: Die Sehnen der Hinterbeine federn wie Sprungfedern.',
      'Zum Abkühlen lecken sie sich die Unterarme - die verdunstende Feuchtigkeit kühlt das Blut.',
    ],
    beobachten:
      'In der Mittagshitze dösen Kängurus im Schatten - morgens und am späten Nachmittag sind sie in Bewegung.',
  },
  {
    id: 'onager',
    name: 'Onager',
    lateinisch: 'Equus hemionus onager',
    bereich: 'asien',
    station: 'kamele',
    kurz: 'Der Halbesel aus Persien - eines der schnellsten und seltensten Wildpferde.',
    steckbrief: {
      Größe: 'Schulterhöhe bis 1,4 m',
      Gewicht: '200 bis 260 kg',
      Alter: '25 bis 30 Jahre',
      Nahrung: 'harte Gräser und Sträucher',
      Heimat: 'Halbwüsten des Iran',
      Status: 'Wildbestand stark bedroht',
    },
    text: [
      'Der Onager ist ein Halbesel: kein Esel und kein Pferd, sondern eine eigene Wildform dazwischen. In seiner iranischen Heimat leben nur noch wenige hundert Tiere in zwei Schutzgebieten.',
      'Halbesel sind die Sprinter unter den Pferdeartigen - kurzzeitig erreichen sie 70 km/h und halten hohes Tempo länger durch als die meisten Verfolger.',
      'An das Leben in der Halbwüste sind Onager bestens angepasst: Sie kommen tagelang mit wenig Wasser aus und fressen Pflanzen, die andere Pflanzenfresser stehen lassen.',
      'Zoos betreiben für den Onager ein europäisches Erhaltungszuchtprogramm - Nachzuchten wurden bereits im Iran und in Saudi-Arabien ausgewildert.',
    ],
    wusstest: [
      'Schon in der Antike galten Onager als unzähmbar - anders als Esel liessen sie sich nie als Lasttiere halten.',
      'Der dunkle Aalstrich auf dem Rücken ist bei jedem Tier unterschiedlich breit.',
      'Onager wälzen sich täglich im Sand - das pflegt Haut und Fell.',
    ],
    beobachten:
      'Onager wirken unscheinbar - aber du siehst hier eines der seltensten Huftiere, die ein Zoo zeigen kann.',
  },
  {
    id: 'tapir',
    name: 'Flachlandtapir',
    lateinisch: 'Tapirus terrestris',
    bereich: 'suedamerika',
    station: 'alpakas',
    kurz: 'Der Urzeit-Pflanzenfresser mit dem Mini-Rüssel - Verwandter von Pferd und Nashorn.',
    steckbrief: {
      Größe: 'bis 2,2 m Körperlänge',
      Gewicht: '150 bis 250 kg',
      Alter: '25 bis 30 Jahre',
      Nahrung: 'Blätter, Wasserpflanzen, Früchte',
      Heimat: 'Regenwälder Südamerikas, immer in Wassernähe',
      Status: 'gefährdet (IUCN: vulnerable)',
    },
    text: [
      'Tapire sehen aus wie eine Mischung aus Schwein und Ameisenbär, sind aber mit Pferden und Nashörnern verwandt. Ihre Körperform hat sich seit Jahrmillionen kaum verändert.',
      'Der kurze Rüssel ist eine bewegliche Greifnase: Damit zupfen Tapire Blätter und ertasten Früchte. Unter Wasser dient er als Schnorchel - Tapire sind ausgezeichnete Schwimmer und flüchten bei Gefahr in den Fluss.',
      'Die Jungtiere kommen mit hellen Streifen und Punkten zur Welt - eine Tarnung wie Lichtflecken auf dem Waldboden, die nach einem halben Jahr verblasst.',
    ],
    wusstest: [
      'Tapire können beim Tauchen über den Grund eines Flusses laufen.',
      'Ihre Fußspuren haben vorne vier und hinten drei Zehen.',
      'Als Samenverbreiter sind Tapire Gärtner des Regenwalds.',
    ],
    beobachten: 'Auf die Nase achten: Der kleine Rüssel ist ständig in Bewegung, wie ein tastender Finger.',
  },
  {
    id: 'wasserschwein',
    name: 'Wasserschwein',
    lateinisch: 'Hydrochoerus hydrochäris',
    bereich: 'suedamerika',
    station: 'alpakas',
    kurz: 'Das größte Nagetier der Welt - ein Meerschweinchen im XXL-Format.',
    steckbrief: {
      Größe: 'bis 1,3 m Körperlänge',
      Gewicht: '35 bis 65 kg',
      Alter: '8 bis 12 Jahre',
      Nahrung: 'Gräser und Wasserpflanzen',
      Heimat: 'Flussufer und Sümpfe Südamerikas',
      Status: 'nicht gefährdet (IUCN: least concern)',
    },
    text: [
      'Wasserschweine - auch Capybaras genannt - sind die größten Nagetiere der Erde und nahe Verwandte der Meerschweinchen.',
      'Ihr Körper ist fürs Wasser gebaut: Augen, Ohren und Nase liegen oben auf dem Kopf, sodass ein fast untergetauchtes Capybara noch alles mitbekommt. Zwischen den Zehen sitzen Schwimmhäute.',
      'Sie leben in Gruppen von zehn bis dreissig Tieren und gelten als ausgesprochen friedlich - in Südamerika sitzen oft Vögel auf ihren Rücken und picken Insekten aus dem Fell.',
    ],
    wusstest: [
      'Capybaras können mehrere Minuten tauchen und sogar im Wasser dösen.',
      'Ihre Schneidezähne wachsen lebenslang nach - wie bei allen Nagetieren.',
      'In vielen Zoos gelten sie als die entspanntesten Tiere überhaupt.',
    ],
    beobachten: 'Wenn ein Capybara ins Wasser geht, schau auf den Kopf: Er bleibt wie ein kleines U-Boot-Periskop über der Oberfläche.',
  },
  {
    id: 'nasenbaer',
    name: 'Weißrüssel-Nasenbär',
    lateinisch: 'Nasua narica',
    bereich: 'suedamerika',
    station: 'alpakas',
    kurz: 'Der neugierige Schnüffler mit dem Ringelschwanz-Antennenmast.',
    steckbrief: {
      Größe: '40 bis 70 cm plus ebenso langer Schwanz',
      Gewicht: '3 bis 6 kg',
      Alter: '14 bis 17 Jahre',
      Nahrung: 'Allesfresser - Insekten, Früchte, Kleintiere',
      Heimat: 'Wälder Mittel- und Südamerikas',
      Status: 'nicht gefährdet (IUCN: least concern)',
    },
    text: [
      'Nasenbären gehören zur Familie der Kleinbären - wie die Waschbären. Mit der beweglichen, rüsselartigen Nase durchwühlen sie das Laub nach Insekten und Früchten.',
      'Die Weibchen leben mit dem Nachwuchs in Gruppen von bis zu zwanzig Tieren, die Männchen meist allein. Beim Laufen tragen alle den geringelten Schwanz senkrecht nach oben - so verliert die Gruppe im hohen Gras niemanden.',
      'Nasenbären klettern hervorragend: Ihre Fußgelenke lassen sich umklappen, sodass sie kopfvoran einen Stamm hinunterlaufen können.',
    ],
    wusstest: [
      'Die Nasenspitze lässt sich um fast 60 Grad in jede Richtung biegen.',
      'Nasenbären sind tagaktiv - anders als die meisten ihrer Verwandten.',
      'Zum Schlafen bauen sie sich Blattnester in Baumkronen.',
    ],
    beobachten: 'Die aufgestellten Ringelschwänze verraten sofort, wo die Gruppe gerade unterwegs ist.',
  },
  {
    id: 'pavian',
    name: 'Mantelpavian',
    lateinisch: 'Papio hamadryas',
    bereich: 'afrika',
    station: 'japangarten',
    kurz: 'Der Affe mit der Silbermähne - lebt in einer Gesellschaft mit strengen Regeln.',
    steckbrief: {
      Größe: 'Männchen bis 80 cm Körperlänge',
      Gewicht: 'Männchen bis 30 kg, Weibchen halb so schwer',
      Alter: '25 bis 35 Jahre',
      Nahrung: 'Allesfresser - Gräser, Wurzeln, Insekten',
      Heimat: 'Felsige Trockengebiete am Horn von Afrika und in Arabien',
      Status: 'nicht gefährdet (IUCN: least concern)',
    },
    text: [
      'Ausgewachsene Mantelpavian-Männchen tragen eine prächtige silbergraue Mähne - den namensgebenden Mantel. Im alten Ägypten galten sie als heilige Tiere des Gottes Thot.',
      'Ihre Gesellschaft ist mehrstufig aufgebaut: Ein Männchen führt eine kleine Familiengruppe, mehrere Familien ziehen als Clan umher, und am Schlaffelsen versammeln sich abends hunderte Tiere.',
      'Der Pavian-Felsen im Tierpark bildet genau das nach: Klettern, Fellpflege und kleine Rangeleien sind hier den ganzen Tag zu sehen.',
    ],
    wusstest: [
      'Paviane schlafen im Sitzen auf schmalen Felsvorsprüngen - ihr Gesäss hat dafür dicke Sitzschwielen.',
      'Fellpflege ist ihre Währung: Wer gut pflegt, hat Verbündete.',
      'Ein Pavian-Gähnen mit gezeigten Eckzähnen ist eine Drohung, kein Müdigkeitszeichen.',
    ],
    beobachten: 'Such das Männchen mit der mächtigsten Mähne - es ist fast immer der Chef der größten Gruppe.',
  },
  {
    id: 'pelikan',
    name: 'Rosa Pelikan',
    lateinisch: 'Pelecanus onocrotalus',
    bereich: 'afrika',
    station: 'japangarten',
    kurz: 'Der Vogel mit dem eingebauten Kescher unter dem Schnabel.',
    steckbrief: {
      Größe: 'bis 1,7 m, Spannweite bis 3,3 m',
      Gewicht: '9 bis 15 kg',
      Alter: '20 bis 30 Jahre',
      Nahrung: 'Fisch',
      Heimat: 'Seen und Lagunen in Afrika und Südosteuropa',
      Status: 'nicht gefährdet (IUCN: least concern)',
    },
    text: [
      'Der Hautbeutel unter dem Pelikanschnabel fasst bis zu 13 Liter - mehr als der Magen des Vogels. Er ist kein Vorratssack, sondern ein Kescher: Wasser wird herausgedrückt, der Fisch bleibt drin.',
      'Rosa Pelikane fischen im Team: Eine Gruppe schwimmt im Halbkreis, treibt die Fische ins flache Wasser und taucht dann gleichzeitig die Schnäbel ein.',
      'Trotz ihrer Größe sind Pelikane elegante Flieger: Luftsäcke unter der Haut und in den Knochen machen sie leicht, und in der Thermik segeln sie stundenlang fast ohne Flügelschlag.',
    ],
    wusstest: [
      'Beim Brütten trägt der Rosa Pelikan einen zarten rosa Schimmer im Gefieder - daher der Name.',
      'Ein Pelikan frisst rund ein Kilogramm Fisch am Tag.',
      'Pelikane gehören zu den schwersten flugfähigen Vögeln der Welt.',
    ],
    beobachten: 'Mit etwas Glück siehst du das Gruppenfischen - eine der besten Teamleistungen im Tierreich.',
  },
  {
    id: 'meerschweinchen',
    name: 'Meerschweinchen',
    lateinisch: 'Cavia porcellus',
    bereich: 'kinder',
    station: 'streichelgehege',
    kurz: 'Die quiekenden Anden-Nager - seit Jahrtausenden beim Menschen zu Hause.',
    steckbrief: {
      Größe: '20 bis 35 cm',
      Gewicht: '700 bis 1.500 g',
      Alter: '4 bis 8 Jahre',
      Nahrung: 'Heu, Gras, Gemüse',
      Heimat: 'Haustierform, ursprünglich Anden Südamerikas',
      Status: 'Haustier',
    },
    text: [
      'Meerschweinchen wurden schon vor über 3.000 Jahren von den Völkern der Anden gehalten - sie gehören zu den ältesten Haustieren Amerikas.',
      'Sie sind ausgesprochene Gruppentiere mit einer eigenen Sprache: Quieken, Gurren, Zähneklappern - Forscher unterscheiden über ein Dutzend Laute mit verschiedenen Bedeutungen.',
      'Mit dem Meer haben sie nichts zu tun: Der Name kommt wohl daher, dass die Tiere übers Meer nach Europa kamen und wie kleine Schweinchen quieken.',
    ],
    wusstest: [
      'Meerschweinchen können ihr eigenes Vitamin C nicht bilden - genau wie wir Menschen.',
      'Wenn sie sich freuen, machen sie Luftsprünge - das nennt man Popcornen.',
      'Ihre Zähne wachsen ein Leben lang nach.',
    ],
    beobachten: 'Hör auf das Quieken: Lautes Pfeifen heißt meist "Futter kommt!".',
    kinder: true,
  },
  {
    id: 'kaninchen',
    name: 'Hasenkaninchen',
    lateinisch: 'Oryctolagus cuniculus',
    bereich: 'kinder',
    station: 'streichelgehege',
    kurz: 'Sieht aus wie ein Hase, ist aber ein Kaninchen - mit Löffeln als Klimaanlage.',
    steckbrief: {
      Größe: '40 bis 50 cm',
      Gewicht: '3 bis 5 kg',
      Alter: '8 bis 12 Jahre',
      Nahrung: 'Heu, Gras, Kräuter',
      Heimat: 'Haustierrasse, Wildform aus Südwesteuropa',
      Status: 'Haustierrasse',
    },
    text: [
      'Das Hasenkaninchen ist eine schlanke, hochbeinige Kaninchenrasse, die einem Feldhasen zum Verwechseln ähnlich sieht - und doch ein echtes Kaninchen ist.',
      'Der Unterschied ist leicht zu merken: Hasen leben allein über der Erde und flüchten ins offene Feld, Kaninchen leben gesellig in unterirdischen Bauen.',
      'Die langen Ohren - Löffel genannt - sind Hörgerät und Klimaanlage zugleich: Über die stark durchbluteten Ohrmuscheln gibt das Tier Wärme ab.',
    ],
    wusstest: [
      'Kaninchen können ihre Ohren unabhängig voneinander drehen.',
      'Beim Flüchten schlagen sie Haken mit blitzschnellen Richtungswechseln.',
      'Klopfen mit den Hinterläufen ist ein Alarmsignal für die ganze Gruppe.',
    ],
    beobachten: 'Achte auf die Körperhaltung: aufgerichtete Ohren und Männchen-Stellung heißt "hier ist etwas Interessantes".',
    kinder: true,
  },
  {
    id: 'ara',
    name: 'Grünflügel-Ara',
    lateinisch: 'Ara chloropterus',
    bereich: 'suedamerika',
    station: 'japangarten',
    kurz: 'Der Riesenpapagei mit dem Nussknacker-Schnabel - und Treue fürs Leben.',
    steckbrief: {
      Größe: 'bis 95 cm mit Schwanz',
      Gewicht: '1 bis 1,7 kg',
      Alter: '50 bis 60 Jahre, teils älter',
      Nahrung: 'Nüsse, Samen, Früchte',
      Heimat: 'Regenwälder Südamerikas',
      Status: 'nicht gefährdet, regional rückgängig',
    },
    text: [
      'Grünflügel-Aras gehören zu den größten Papageien der Welt. Ihr Schnabel knackt selbst steinharte Paranüsse - eine der stärksten Beisskräfte unter allen Vögeln.',
      'Aras leben in lebenslangen Paaren. Die Partner fliegen so dicht nebeneinander, dass sich ihre Flügel fast berühren, und pflegen sich gegenseitig das Gefieder.',
      'Im Arahaus wohnen neben den Aras auch Sechsbinden-Gürteltiere - südamerikanische Panzertiere, die sich bei Gefahr aber nicht einrollen, sondern blitzschnell eingraben.',
    ],
    wusstest: [
      'Aras nutzen ihren Schnabel beim Klettern als dritten Fuß.',
      'Wilde Aras fressen an Lehmwänden - die Mineralien helfen bei der Verdauung.',
      'Papageienzehen greifen paarweise: zwei nach vorn, zwei nach hinten.',
    ],
    beobachten: 'Schau auf die Gesichter: Die feinen roten Federlinien auf der weißen Wange sind bei jedem Ara anders.',
  },
  {
    id: 'kranich',
    name: 'Mandschurenkranich',
    lateinisch: 'Grus japonensis',
    bereich: 'asien',
    station: 'seeloewen',
    kurz: 'Der Glücksvogel Ostasiens - berühmt für seinen Hochzeitstanz.',
    steckbrief: {
      Größe: 'bis 1,6 m',
      Gewicht: '7 bis 10 kg',
      Alter: '30 bis 60 Jahre',
      Nahrung: 'Fische, Insekten, Pflanzen',
      Heimat: 'Feuchtgebiete in Ostasien',
      Status: 'gefährdet - einer der seltensten Kraniche der Welt',
    },
    text: [
      'In China und Japan gilt der Mandschurenkranich seit Jahrhunderten als Symbol für Glück, Treue und langes Leben - kaum ein Vogel wird in der Kunst Ostasiens häufiger dargestellt.',
      'Berühmt ist sein Tanz: Paare springen mit ausgebreiteten Flügeln umeinander, verbeugen sich und werfen Gegenstände in die Luft. Getanzt wird nicht nur zur Balz, sondern das ganze Jahr.',
      'In freier Wildbahn leben nur noch wenige tausend Tiere. Kraniche bleiben ein Leben lang zusammen und rufen im Dütt - so eng abgestimmt, dass es wie ein einziger Vogel klingt.',
    ],
    wusstest: [
      'Die rote Kopfplatte ist keine Feder, sondern nackte Haut - bei Aufregung leuchtet sie kräftiger.',
      'Kranichküken können schon wenige Stunden nach dem Schlupf laufen.',
      'Nebenan stolzieren auch Störche und weitere Kranicharten durch die Anlagen.',
    ],
    beobachten: 'Mit Glück siehst du den Tanz - bleib stehen, wenn zwei Vögel beginnen, sich voreinander zu verbeugen.',
  },
  {
    id: 'muntjak',
    name: 'Chinesischer Muntjak',
    lateinisch: 'Muntiacus reevesi',
    bereich: 'asien',
    station: 'seeloewen',
    kurz: 'Der kleine Hirsch, der bellt wie ein Hund.',
    steckbrief: {
      Größe: 'Schulterhöhe etwa 50 cm',
      Gewicht: '10 bis 17 kg',
      Alter: '10 bis 18 Jahre',
      Nahrung: 'Blätter, Knospen, Früchte',
      Heimat: 'Wälder Südostchinas und Taiwans',
      Status: 'nicht gefährdet (IUCN: least concern)',
    },
    text: [
      'Muntjaks werden auch Bellhirsche genannt: Bei Gefahr stoßen sie laute, hundeähnliche Bell-Laute aus - manchmal minutenlang.',
      'Die Böcke tragen ein winziges Geweih auf langen, fellbedeckten Stielen - und zusätzlich verlängerte obere Eckzähne, die wie kleine Hauer aus dem Maul ragen. Gekämpft wird mehr mit den Zähnen als mit dem Geweih.',
      'Muntjaks gehören zu den ältesten Hirschen der Welt: Fossilien zeigen, dass es sie seit Millionen Jahren fast unverändert gibt.',
    ],
    wusstest: [
      'Muntjaks leben einzeln - ungewöhnlich für Hirsche.',
      'Vor den Augen sitzen große Duftdrüsen, mit denen sie ihr Revier markieren.',
      'Sie sind kaum größer als ein Dackel auf langen Beinen.',
    ],
    beobachten: 'Schau genau ins Gehege - Muntjaks stehen oft reglos im Schatten und sind leicht zu übersehen.',
  },
  {
    id: 'pinselohrschwein',
    name: 'Pinselohrschwein',
    lateinisch: 'Potamochoerus porcus',
    bereich: 'afrika',
    station: 'afrikapanorama',
    kurz: 'Das schönste Schwein der Welt - rostrot mit weißen Ohrpinseln.',
    steckbrief: {
      Größe: 'bis 1,5 m Körperlänge',
      Gewicht: '50 bis 120 kg',
      Alter: '15 bis 20 Jahre',
      Nahrung: 'Allesfresser - Wurzeln, Früchte, Kleintiere',
      Heimat: 'Regenwälder West- und Zentralafrikas',
      Status: 'nicht gefährdet (IUCN: least concern)',
    },
    text: [
      'Mit leuchtend rostrotem Fell, weissem Aalstrich und langen weißen Haarpinseln an den Ohren gelten Pinselohrschweine als die farbenprächtigsten Wildschweine der Welt.',
      'Sie leben in Familiengruppen im dichten Regenwald und sind vor allem in der Dämmerung aktiv. Mit der kräftigen Schnauze pflügen sie den Waldboden nach Wurzeln und Knollen um.',
      'Pinselohrschweine schwimmen gern und gut - in ihrer Heimat durchqueren sie regelmäßig Flüsse.',
    ],
    wusstest: [
      'Die Ohrpinsel dienen wohl der Verständigung im dunklen Unterholz.',
      'Frischlinge tragen wie heimische Wildschweine gestreifte Tarnkleidung.',
      'Ihr Geruchssinn findet Futter auch unter 30 Zentimetern Erde.',
    ],
    beobachten: 'Im Sonnenlicht leuchtet das rote Fell wie Kupfer - der beste Fotomoment.',
  },
  {
    id: 'stachelschwein',
    name: 'Weissschwanz-Stachelschwein',
    lateinisch: 'Hystrix indica',
    bereich: 'asien',
    station: 'loewen',
    kurz: 'Ein Nagetier in Ritterrüstung - mit rasselndem Warnschwanz.',
    steckbrief: {
      Größe: '70 bis 90 cm',
      Gewicht: '11 bis 18 kg',
      Alter: '15 bis 20 Jahre',
      Nahrung: 'Wurzeln, Knollen, Früchte, Rinde',
      Heimat: 'Vorder- und Südasien',
      Status: 'nicht gefährdet (IUCN: least concern)',
    },
    text: [
      'Stachelschweine sind weder Schweine noch mit Igeln verwandt - sie sind große Nagetiere. Ihre bis zu 40 Zentimeter langen Stacheln sind umgebaute Haare.',
      'Bei Gefahr stellt das Tier die Stacheln auf, rasselt mit hohlen Schwanzstacheln wie mit einer Rassel und läuft notfalls rückwärts auf den Angreifer zu. Die Stacheln lösen sich leicht und bleiben im Gegner stecken - geschossen werden sie aber nicht.',
      'Tagsüber ruhen Stachelschweine in selbstgegrabenen Bauen, nachts ziehen sie auf Futtersuche.',
    ],
    wusstest: [
      'Selbst Löwen und Leoparden lassen erwachsene Stachelschweine meist in Ruhe.',
      'Die Nagezähne wachsen ständig - Knochen und Rinde dienen als Feile.',
      'Stachelschwein-Paare bleiben ein Leben lang zusammen.',
    ],
    beobachten: 'Abends am aktivsten - tagsüber verrät oft nur ein Stachelbündel im Bau-Eingang das Tier.',
  },
  {
    id: 'serval',
    name: 'Serval',
    lateinisch: 'Leptailurus serval',
    bereich: 'afrika',
    station: 'loewen',
    kurz: 'Die Katze auf Stelzen - springt drei Meter hoch nach Mäusen.',
    steckbrief: {
      Größe: 'Schulterhöhe bis 62 cm',
      Gewicht: '9 bis 18 kg',
      Alter: '15 bis 20 Jahre',
      Nahrung: 'Nagetiere, Vögel, Frösche',
      Heimat: 'Feuchte Savannen Afrikas',
      Status: 'nicht gefährdet (IUCN: least concern)',
    },
    text: [
      'Im Verhältnis zum Körper hat der Serval die längsten Beine aller Katzen - und riesige Ohren, mit denen er Mäuse selbst unter der Erde hört.',
      'Seine Jagdtechnik ist spektakulär: Er ortet die Beute allein nach Gehör im hohen Gras, springt in hohem Bogen und schlägt mit beiden Vorderpfoten zu. Bis zu drei Meter hoch und vier Meter weit reichen seine Sprünge.',
      'Anders als viele Katzen scheut der Serval kein Wasser und fischt gelegentlich Frösche aus Tümpeln.',
    ],
    wusstest: [
      'Etwa jede zweite Sprungattacke ist erfolgreich - ein Spitzenwert unter Katzen.',
      'Die Ohrmuscheln lassen sich unabhängig voneinander drehen wie Radarantennen.',
      'Servale können Vögel im Flug aus der Luft schlagen.',
    ],
    beobachten: 'Wenn der Serval den Kopf schräg legt und die Ohren spitzt, hat er etwas gehört - vielleicht folgt gleich der Sprung.',
  },
  {
    id: 'kudu',
    name: 'Großer Kudu',
    lateinisch: 'Tragelaphus strepsiceros',
    bereich: 'afrika',
    station: 'afrikapanorama',
    kurz: 'Die Antilope mit den Schraubenhörnern - königliche Erscheinung der Savanne.',
    steckbrief: {
      Größe: 'Schulterhöhe bis 1,5 m',
      Gewicht: 'Bullen bis 270 kg',
      Alter: '15 bis 20 Jahre',
      Nahrung: 'Blätter, Triebe, Kräuter',
      Heimat: 'Busch- und Waldsavannen im östlichen und südlichen Afrika',
      Status: 'nicht gefährdet (IUCN: least concern)',
    },
    text: [
      'Die Hörner der Kudu-Bullen drehen sich in bis zu drei vollen Schrauben und erreichen ausgestreckt weit über einen Meter - die eindrucksvollsten Hörner aller Antilopen.',
      'Trotz ihrer Größe sind Kudus Meister im Verschwinden: Die weißen Querstreifen auf dem graubraunen Fell lösen die Körperkontur im Buschwerk auf.',
      'Auf der Savannen-Anlage leben Kudus mit Impalas, Elenantilopen und Hornraben zusammen - so entsteht das Bild einer afrikanischen Lebensgemeinschaft.',
    ],
    wusstest: [
      'Kudus springen aus dem Stand über zweieinhalb Meter hohe Hindernisse.',
      'Nur die Bullen tragen Hörner.',
      'Ihre großen Ohren machen sie zu ausgezeichneten Lauschern.',
    ],
    beobachten: 'Zähl die Schraubenwindungen - je mehr Drehungen, desto älter der Bulle.',
  },
  {
    id: 'maehnenspringer',
    name: 'Mähnenspringer',
    lateinisch: 'Ammotragus lervia',
    bereich: 'afrika',
    station: 'afrikapanorama',
    kurz: 'Der Kletterkünstler aus der Wüste mit dem Vorhang aus Haaren.',
    steckbrief: {
      Größe: 'Schulterhöhe bis 1 m',
      Gewicht: '40 bis 140 kg',
      Alter: '15 bis 20 Jahre',
      Nahrung: 'Gräser, Kräuter, Sträucher',
      Heimat: 'Gebirge der Sahara und Nordafrikas',
      Status: 'gefährdet (IUCN: vulnerable)',
    },
    text: [
      'Mähnenspringer stehen zwischen Ziegen und Schafen - und tragen ihr auffälligstes Merkmal an Kehle und Vorderbeinen: einen langen Behang aus weichen Haaren.',
      'In den Wüstengebirgen ihrer Heimat klettern sie über fast senkrechte Felswände. Ihr Trick ist der Absprung: Von winzigen Vorsprüngen stoßen sie sich ab und landen zielgenau auf der nächsten Kante.',
      'Wasser brauchen sie kaum - den Flüssigkeitsbedarf decken sie weitgehend über die Nahrung und Tau.',
    ],
    wusstest: [
      'Bei Gefahr bleiben Mähnenspringer völlig reglos stehen - ihre Fellfarbe verschmilzt mit dem Fels.',
      'Auch die Weibchen tragen Hörner, nur kleiner.',
      'Der Hagenbeck-Felsen für die Mähnenspringer stammt aus der Anfangszeit des Parks.',
    ],
    beobachten: 'Schau nach oben: Die Tiere stehen am liebsten auf dem höchsten Punkt ihres Felsens.',
  },
  {
    id: 'tahr',
    name: 'Himalaya-Tahr',
    lateinisch: 'Hemitragus jemlahicus',
    bereich: 'asien',
    station: 'afrikapanorama',
    kurz: 'Die Bergziege aus dem Himalaya mit der Löwenmähne.',
    steckbrief: {
      Größe: 'Schulterhöhe bis 1 m',
      Gewicht: '35 bis 90 kg',
      Alter: '15 bis 20 Jahre',
      Nahrung: 'Gräser, Kräuter, Laub',
      Heimat: 'Steile Hänge des Himalaya, 2.500 bis 5.000 m Höhe',
      Status: 'Vorwarnliste (IUCN: near threatened)',
    },
    text: [
      'Der Himalaya-Tahr ist eine Wildziege, deren Böcke im Winter eine mächtige, hellblonde Halsmähne tragen - fast wie ein Löwe im Bergformat.',
      'Seine Hufe haben weiche, gummiartige Sohlenballen mit harten Rändern - eine natürliche Kletterausrüstung für Felsplatten und Eiskanten.',
      'In der dünnen Höhenluft des Himalaya ist der Tahr einer der höchstlebenden großen Pflanzenfresser der Erde.',
    ],
    wusstest: [
      'Das dichte Winterfell schützt bei Temperaturen weit unter minus 20 Grad.',
      'Im Sommer wandern Tahre bergauf, im Winter in tiefere Lagen - ihr Jahresrhythmus ist ein Höhenpendel.',
      'Der Tahr-Felsen gehört zu den historischen Kunstfelsen des Parks.',
    ],
    beobachten: 'Vergleiche die Mähnen: Je prächtiger der helle Kragen, desto älter der Bock.',
  },
  {
    id: 'tamarin',
    name: 'Tamarine',
    lateinisch: 'Saguinus',
    bereich: 'suedamerika',
    station: 'flamingoteich',
    kurz: 'Handtellergrosse Äffchen - und die Väter tragen die Kinder.',
    steckbrief: {
      Größe: '20 bis 30 cm plus langer Schwanz',
      Gewicht: '300 bis 550 g',
      Alter: '10 bis 18 Jahre',
      Nahrung: 'Insekten, Früchte, Baumsäfte',
      Heimat: 'Regenwälder Südamerikas',
      Status: 'je nach Art unterschiedlich',
    },
    text: [
      'Tamarine gehören zu den Krallenaffen - den kleinsten Affen der Welt. Statt Nägeln tragen sie Krallen, mit denen sie wie Eichhörnchen an Stämmen klettern.',
      'Bei der Jungenaufzucht sind die Rollen getauscht: Meist trägt der Vater die Zwillinge auf dem Rücken und gibt sie der Mutter nur zum Säugen.',
      'Im Haus teilen sich die Tamarine den Platz mit Sakis und Trompetervögeln - ein kleines Stück südamerikanischer Regenwald.',
    ],
    wusstest: [
      'Zwillinge sind bei Tamarinen der Normalfall, nicht die Ausnahme.',
      'Ältere Geschwister helfen bei der Aufzucht der Kleinen mit.',
      'Ihre hohen Pfiffe klingen eher nach Vogel als nach Affe.',
    ],
    beobachten: 'Schau auf die Rücken der Erwachsenen - oft klammern sich dort die Jungtiere fest.',
  },
  {
    id: 'praeriehund',
    name: 'Präriehund',
    lateinisch: 'Cynomys ludovicianus',
    bereich: 'amerika',
    station: 'spielplatz',
    kurz: 'Die Stadtplaner der Prairie - mit eigener Sprache und Kuss-Begrüssung.',
    steckbrief: {
      Größe: '28 bis 35 cm',
      Gewicht: '700 bis 1.400 g',
      Alter: '5 bis 8 Jahre',
      Nahrung: 'Gräser und Kräuter',
      Heimat: 'Prairien Nordamerikas',
      Status: 'nicht gefährdet, Bestand stark geschrumpft',
    },
    text: [
      'Präriehunde sind keine Hunde, sondern Erdhörnchen. Ihren Namen verdanken sie dem bellenden Warnruf.',
      'Sie bauen unterirdische Städte mit Schlafkammern, Kinderstuben und sogar Hochwasser-Nischen. Historische Kolonien in Texas beherbergten Millionen Tiere.',
      'Ihre Warnrufe gelten als eine der komplexesten Tiersprachen: Für Mensch, Habicht oder Kojote gibt es unterschiedliche Rufe.',
      'Gleich nebenan wohnen die Baumstachler - nordamerikanische Kletternager mit Stachelkleid.',
    ],
    wusstest: [
      'Zur Begrüssung berühren sich Präriehunde mit den Zähnen - es sieht aus wie ein Kuss.',
      'Ein Wächter steht immer aufrecht am Bau, während die anderen fressen.',
      'Der Hügel um den Eingang wirkt als Deich und als Aussichtsturm zugleich.',
    ],
    beobachten: 'Beobachte den aufrecht stehenden Wächter - bellt er, verschwinden alle blitzschnell im Bau.',
  },
  {
    id: 'wapiti',
    name: 'Wapiti',
    lateinisch: 'Cervus canadensis',
    bereich: 'amerika',
    station: 'tiger',
    kurz: 'Der Riesenhirsch Nordamerikas - sein Röhren trägt kilometerweit.',
    steckbrief: {
      Größe: 'Schulterhöhe bis 1,5 m',
      Gewicht: 'Bullen bis 450 kg',
      Alter: '15 bis 20 Jahre',
      Nahrung: 'Gräser, Kräuter, Laub',
      Heimat: 'Nordamerika und Ostasien',
      Status: 'nicht gefährdet (IUCN: least concern)',
    },
    text: [
      'Wapitis gehören zu den größten Hirschen der Welt - deutlich mächtiger als unser Rothirsch, mit dem sie eng verwandt sind.',
      'Das Geweih der Bullen wächst jedes Jahr neu und erreicht über ein Meter Länge und mehr als zehn Kilogramm Gewicht - eine der schnellsten Knochenbildungen im Tierreich.',
      'Zur Brunft im Herbst röhren die Bullen mit einem hohen, pfeifenden Schrei, der kilometerweit trägt - eines der berühmtesten Gerausche der nordamerikanischen Wildnis.',
    ],
    wusstest: [
      'Der Name Wapiti stammt aus einer Indianersprache und bedeutet "weißer Hinterteil".',
      'Im Frühjahr wirft der Bulle sein Geweih ab und schiebt sofort ein neues.',
      'Wapiti-Kälber tragen in den ersten Monaten weiße Tarnflecken.',
    ],
    beobachten: 'Im Spätsommer ist das Geweih mit samtiger Basthaut überzogen - später fegt der Bulle sie an Bäumen ab.',
  },
  {
    id: 'schneeeule',
    name: 'Schnee-Eule',
    lateinisch: 'Bubo scandiacus',
    bereich: 'eismeer',
    station: 'tiger',
    kurz: 'Die weiße Jägerin der Arktis - jagt auch am helllichten Tag.',
    steckbrief: {
      Größe: 'bis 66 cm, Spannweite bis 1,7 m',
      Gewicht: '1,6 bis 3 kg',
      Alter: '15 bis 25 Jahre',
      Nahrung: 'Lemminge und andere Kleinsäuger',
      Heimat: 'Arktische Tundra rund um den Polarkreis',
      Status: 'gefährdet (IUCN: vulnerable)',
    },
    text: [
      'Anders als die meisten Eulen jagt die Schnee-Eule auch tagsüber - im arktischen Sommer geht die Sonne schließlich wochenlang nicht unter.',
      'Ihr Gefieder reicht bis über die Zehen: Die befiederten Füße wirken wie Daunenstiefel gegen die Polarkälte.',
      'Männchen werden mit den Jahren fast reinweiß, Weibchen behalten dunkle Sprenkel - so sind sie am Boden brütend zwischen Flechten und Steinen getarnt.',
    ],
    wusstest: [
      'In guten Lemming-Jahren zieht eine Schnee-Eule doppelt so viele Junge groß wie sonst.',
      'Der Kopf lässt sich um bis zu 270 Grad drehen.',
      'Ihr Flug ist dank weicher Federkanten fast lautlos.',
    ],
    beobachten: 'Schnee-Eulen sitzen gern lange reglos am Boden - such nach dem weißen Fleck mit den leuchtend gelben Augen.',
  },
  {
    id: 'riesenschildkroete',
    name: 'Riesenschildkröten',
    lateinisch: 'Aldabrachelys gigantea',
    bereich: 'garten',
    station: 'orangutans',
    kurz: 'Gepanzerte Methusalems - älter als jeder Mensch.',
    steckbrief: {
      Größe: 'Panzer bis 1,2 m',
      Gewicht: 'bis 250 kg',
      Alter: 'weit über 100 Jahre',
      Nahrung: 'Gräser, Kräuter, Blätter',
      Heimat: 'Aldabra-Atoll im Indischen Ozean',
      Status: 'gefährdet (IUCN: vulnerable)',
    },
    text: [
      'Riesenschildkröten gehören zu den langlebigsten Tieren der Erde - einzelne Tiere haben nachweislich mehr als 150 Jahre gelebt.',
      'Ihr Panzer ist kein aufgesetzter Schutzschild, sondern Teil des Skeletts: Rippen und Wirbel sind mit den Knochenplatten verwachsen. Ausziehen unmöglich.',
      'Zähne haben Schildkröten keine - sie schneiden Pflanzen mit scharfen Hornkanten ihres Kiefers ab. Neben der Anlage erinnern Saurierfiguren an die Urzeit-Verwandtschaft der Reptilien.',
    ],
    wusstest: [
      'Eine Riesenschildkröte kann ein Jahr ohne Nahrung überleben - so besiedelten ihre Vorfahren treibend ferne Inseln.',
      'Am kräftigen Hals erkennen Forscher, ob ein Tier eher Gras frisst oder nach Blättern streckt.',
      'Trotz 250 Kilo Gewicht schläfert eine Berührung am Panzer die Tiere nicht - sie spüren sie deutlich.',
    ],
    beobachten: 'Morgens sind die Tiere am aktivsten, mittags parken sie oft wie Felsen in der Sonne.',
  },
  {
    id: 'zwergotter',
    name: 'Zwergotter',
    lateinisch: 'Aonyx cinereus',
    bereich: 'asien',
    station: 'orangutans',
    kurz: 'Der kleinste Otter der Welt - mit Fingern fast wie unsere.',
    steckbrief: {
      Größe: '40 bis 60 cm plus Schwanz',
      Gewicht: '2 bis 5 kg',
      Alter: '10 bis 15 Jahre',
      Nahrung: 'Krebse, Muscheln, Schnecken, kleine Fische',
      Heimat: 'Feuchtgebiete Südostasiens',
      Status: 'gefährdet (IUCN: vulnerable)',
    },
    text: [
      'Zwergotter sind die kleinsten Otter der Welt - und die geschicktesten: Ihre Vorderpfoten haben kurze Krallen und bewegliche Finger, mit denen sie unter Steinen nach Krebsen tasten wie wir mit bloßen Händen.',
      'Sie leben in Grossfamilien von bis zu fünfzehn Tieren, die ältere Geschwister helfen bei der Aufzucht der Jüngsten.',
      'Im Orang-Utan-Haus sind die Zwergotter die quirligen Untermieter - ständig in Bewegung, ständig zu hören.',
    ],
    wusstest: [
      'Zwergotter jonglieren mit Steinchen - vermutlich Training für die Fingerfertigkeit.',
      'Mit über einem Dutzend Rufen gehören sie zu den gesprächigsten Ottern.',
      'Harte Muscheln legen sie in die Sonne, bis sie sich von selbst öffnen.',
    ],
    beobachten: 'Achte auf die Pfoten: Zwergotter ertasten ihr Futter, statt es mit dem Maul zu suchen.',
  },
  {
    id: 'mara',
    name: 'Großer Mara',
    lateinisch: 'Dolichotis patagonum',
    bereich: 'suedamerika',
    station: 'alpakawiese',
    kurz: 'Sieht aus wie ein Hase auf Rehbeinen - und ist ein treues Nagetier.',
    steckbrief: {
      Größe: '60 bis 80 cm',
      Gewicht: '8 bis 16 kg',
      Alter: '10 bis 14 Jahre',
      Nahrung: 'Gräser und Kräuter',
      Heimat: 'Pampa Argentiniens',
      Status: 'Vorwarnliste (IUCN: near threatened)',
    },
    text: [
      'Maras - auch Pampashasen genannt - gehören trotz Hasenohren und Rehbeinen zu den Nagetieren und sind mit den Meerschweinchen verwandt.',
      'Mara-Paare bleiben ein Leben lang zusammen - eine Seltenheit unter Säugetieren. Das Männchen weicht seiner Partnerin kaum von der Seite.',
      'Mehrere Paare teilen sich eine Gemeinschafts-Kinderstube: Ein großer Bau, in dem alle Jungen der Gruppe wohnen, während die Eltern draußen wachen.',
    ],
    wusstest: [
      'Auf der Flucht schlagen Maras Haken und springen mit allen vier Beinen gleichzeitig ab.',
      'Sie erreichen über 40 km/h und halten das Tempo lange durch.',
      'Beim Sonnenbaden sitzen Maras wie Katzen auf eingeklappten Vorderbeinen.',
    ],
    beobachten: 'Maras sieht man fast immer paarweise - wo eines ist, ist das andere nicht weit.',
  },
  {
    id: 'warzenschwein',
    name: 'Warzenschwein',
    lateinisch: 'Phacochoerus africanus',
    bereich: 'afrika',
    station: 'strausse',
    kurz: 'Der Antennen-Schwanz der Savanne - kniet zum Fressen nieder.',
    steckbrief: {
      Größe: 'bis 1,5 m Körperlänge',
      Gewicht: '50 bis 150 kg',
      Alter: '10 bis 15 Jahre',
      Nahrung: 'Gräser, Wurzeln, Knollen',
      Heimat: 'Savannen Afrikas südlich der Sahara',
      Status: 'nicht gefährdet (IUCN: least concern)',
    },
    text: [
      'Die namensgebenden Warzen sind Hautpolster, die Kopf und Augen bei Kämpfen schützen. Dazu kommen imposante, nach oben gebogene Hauer.',
      'Beim Fressen geht das Warzenschwein auf die Knie: Auf schwieligen Handgelenken rutscht es grasend voran - eine im Tierreich einmalige Haltung.',
      'Rennt eine Warzenschwein-Familie davon, stehen alle Schwänze kerzengerade nach oben - wie kleine Antennen, denen die Frischlinge im hohen Gras folgen können.',
    ],
    wusstest: [
      'Warzenschweine übernachten in verlassenen Erdferkel-Bauen - rückwärts, mit den Hauern zum Eingang.',
      'Schlammbäder sind ihre Klimaanlage und ihr Insektenschutz.',
      'Trotz gemütlichen Aussehens erreichen sie 50 km/h.',
    ],
    beobachten: 'Beim Grasen auf Knien sehen Warzenschweine aus, als würden sie beten - typischer geht es nicht.',
  },
];

/*
 * Touren. minuten = grobe Gehzeit inkl. Aufenthalt.
 * stationen: Reihenfolge der Stationen mit optionalem Fokus-Text.
 */
export const TOUREN = [
  {
    id: 'klassiker',
    titel: 'Die großen Klassiker',
    schwerpunkt: 'Höhepunkte',
    emoji: '⭐',
    minuten: 180,
    laenge: 'ca. 3 km',
    fuer: 'Erster Besuch, Gäste, "einmal alles Wichtige"',
    beschreibung:
      'Die Runde für den ersten Besuch: Eismeer, Elefanten, Afrika-Panorama und die Seebären-Fütterung. Wenig Umwege, alle bekannten Anlagen einmal mitgenommen.',
    stationen: [
      { id: 'haupteingang', fokus: 'Fütterungszeiten am Aushang fotografieren' },
      { id: 'elefanten', fokus: 'Zeit lassen - hier bleiben die meisten am längsten' },
      { id: 'orangutans' },
      { id: 'tiger' },
      { id: 'flamingoteich' },
      { id: 'japangarten', fokus: 'Ruhige Pause auf halber Strecke' },
      { id: 'loewen' },
      { id: 'afrikapanorama', fokus: 'Die berühmte Panorama-Perspektive' },
      { id: 'seeloewen', fokus: 'Zeitlich an der Schaufütterung ausrichten' },
      { id: 'eismeer', fokus: 'Unterwasserfenster nicht auslassen' },
    ],
  },
  {
    id: 'familie',
    titel: 'Mit Kindern durch den Park',
    schwerpunkt: 'Familie',
    emoji: '👨‍👩‍👧',
    minuten: 210,
    laenge: 'ca. 2,5 km',
    fuer: 'Kinder von etwa 3 bis 10 Jahren',
    beschreibung:
      'Kurze Wege, viel Anfassen und Spielen, planbare Pausen. Die Route wechselt bewusst zwischen Tieren schauen und Toben - so hält die Laune länger.',
    stationen: [
      { id: 'haupteingang' },
      { id: 'elefanten' },
      { id: 'kamele' },
      { id: 'alpakas' },
      { id: 'spielplatz', fokus: 'Lange Pause einplanen, Verpflegung in der Nähe' },
      { id: 'flamingoteich', fokus: 'Kurzer Halt am Wasser' },
      { id: 'streichelgehege', fokus: 'Zum Anfassen - Hände waschen nicht vergessen' },
      { id: 'seeloewen', fokus: 'Schaufütterung - für Kinder das Highlight' },
      { id: 'eismeer', fokus: 'Pinguine und Unterwasserfenster' },
    ],
  },
  {
    id: 'eismeer',
    titel: 'Kalte Welten',
    schwerpunkt: 'Polar & Meer',
    emoji: '🧊',
    minuten: 105,
    laenge: 'ca. 1,5 km',
    fuer: 'Halber Tag, heisses Wetter, Eisbären-Fans',
    beschreibung:
      'Konzentriert auf Eismeer und Seebären: Eisbären, Walrosse, Pinguine, Robben. Viel Wasser, viel Schatten, mehrere Unterwasserfenster.',
    stationen: [
      { id: 'haupteingang' },
      { id: 'kamele', fokus: 'Kontrastprogramm: Wüste statt Eis' },
      { id: 'japangarten' },
      { id: 'seeloewen', fokus: 'Schaufütterung mit Erklärungen' },
      { id: 'eismeer', fokus: 'Kernstück - mindestens 40 Minuten' },
    ],
  },
  {
    id: 'afrika',
    titel: 'Savanne & Weite',
    schwerpunkt: 'Afrika',
    emoji: '🦒',
    minuten: 105,
    laenge: 'ca. 1,8 km',
    fuer: 'Panorama-Fans, Fotografen',
    beschreibung:
      'Die Route entlang der Freianlagen, für die Hagenbeck berühmt ist: Zebras, Strauße, Antilopen und die große Panorama-Perspektive - ohne Gitter, nur durch Gräben getrennt.',
    stationen: [
      { id: 'haupteingang' },
      { id: 'loewen' },
      { id: 'afrikapanorama', fokus: 'Der beste Blick des Parks' },
      { id: 'strausse', fokus: 'Zebras und Strauße in einer Anlage' },
      { id: 'flamingoteich' },
      { id: 'elefanten' },
    ],
  },
  {
    id: 'raubtiere',
    titel: 'Jäger & Räuber',
    schwerpunkt: 'Raubtiere',
    emoji: '🐅',
    minuten: 120,
    laenge: 'ca. 2 km',
    fuer: 'Ältere Kinder, Jugendliche',
    beschreibung:
      'Von der Grosskatze bis zum Riffhai: eine Route entlang der Jäger. Am besten am späten Nachmittag - dann sind die meisten Raubtiere wach.',
    stationen: [
      { id: 'haupteingang' },
      { id: 'tiger', fokus: 'Erhöhte Liegeplätze absuchen' },
      { id: 'loewen' },
      { id: 'eismeer', fokus: 'Eisbär - das größte Landraubtier der Welt' },
      { id: 'strausse', fokus: 'Kurzer Schwenk durch die Steppe' },
      { id: 'tropenaquarium', fokus: 'Haie und Krokodile - eigenes Ticket nötig' },
    ],
  },
  {
    id: 'regentag',
    titel: 'Regentag im Trockenen',
    schwerpunkt: 'Schlechtwetter',
    emoji: '🌧️',
    minuten: 150,
    laenge: 'ca. 1,5 km',
    fuer: 'Regen, Kälte, Hitze',
    beschreibung:
      'Maximal viel Zeit unter Dach: Tropen-Aquarium, Menschenaffen-Haus und die Innenbereiche des Eismeers. Kurze Wege zwischen den Gebäuden.',
    stationen: [
      { id: 'haupteingang' },
      { id: 'tropenaquarium', fokus: 'Hauptprogramm - eigenes Ticket nötig' },
      { id: 'elefanten', fokus: 'Elefantenhaus bietet Schutz' },
      { id: 'orangutans', fokus: 'Innenanlage mit großen Scheiben' },
      { id: 'eismeer', fokus: 'Überdachte Abschnitte und Unterwasserwege' },
    ],
  },
  {
    id: 'kurz',
    titel: 'Blitzbesuch in einer Stunde',
    schwerpunkt: 'Wenig Zeit',
    emoji: '⏱️',
    minuten: 60,
    laenge: 'ca. 1,2 km',
    fuer: 'Zwischenstopp, kurzer Besuch',
    beschreibung:
      'Wenn nur eine Stunde bleibt: die drei Anlagen, die man gesehen haben sollte, auf dem kürzesten Weg.',
    stationen: [
      { id: 'haupteingang' },
      { id: 'elefanten', fokus: '15 Minuten reichen für einen guten Eindruck' },
      { id: 'afrikapanorama', fokus: 'Kurz stehenbleiben, Panorama ansehen' },
      { id: 'eismeer', fokus: 'Direkt zu den Unterwasserfenstern durchgehen' },
    ],
  },
  {
    id: 'entspannt',
    titel: 'Entspannt & barrierearm',
    schwerpunkt: 'Ruhige Runde',
    emoji: '♿',
    minuten: 150,
    laenge: 'ca. 1,5 km',
    fuer: 'Kinderwagen, Rollator, Rollstuhl, langsames Tempo',
    beschreibung:
      'Eine kurze Runde mit vielen Sitzgelegenheiten und ohne unnötige Steigungen. Weniger Stationen, dafür mehr Zeit pro Anlage.',
    hinweis:
      'Die Wege im Park sind überwiegend befestigt, es gibt aber Steigungen. Aktuelle Angaben zur Barrierefreiheit stehen auf hagenbeck.de.',
    stationen: [
      { id: 'haupteingang' },
      { id: 'elefanten' },
      { id: 'japangarten', fokus: 'Ruhigster Ort im Park' },
      { id: 'flamingoteich', fokus: 'Bänke direkt am Weg' },
      { id: 'afrikapanorama' },
      { id: 'seeloewen', fokus: 'Sitzplätze an der Tribüne' },
    ],
  },
];

/*
 * Fütterungen und Vorführungen.
 * ACHTUNG: Diese Zeiten sind Platzhalter für die Planung und NICHT amtlich.
 * In den Einstellungen lassen sie sich auf die tatsächlichen Zeiten des
 * Besuchstags anpassen; die Anpassung bleibt auf dem Gerät gespeichert.
 */
export const FUETTERUNGEN = [
  { id: 'seeloewen', titel: 'Schaufütterung Seebären', station: 'seeloewen', zeit: '', hinweis: 'Findet in der Regel täglich statt.' },
  { id: 'eisbaeren', titel: 'Fütterung Eisbären', station: 'eismeer', zeit: '', hinweis: 'Zeiten variieren je nach Tagesablauf.' },
  { id: 'walrosse', titel: 'Fütterung Walrosse', station: 'eismeer', zeit: '', hinweis: 'Oft mit Erklärungen der Pfleger.' },
  { id: 'pinguine', titel: 'Fütterung Pinguine', station: 'eismeer', zeit: '', hinweis: '' },
  { id: 'elefanten', titel: 'Elefanten-Vorführung', station: 'elefanten', zeit: '', hinweis: 'Nur an bestimmten Tagen.' },
  { id: 'haie', titel: 'Fütterung Haie', station: 'tropenaquarium', zeit: '', hinweis: 'Nur an bestimmten Wochentagen.' },
];

/* Öffnungszeiten laut OpenStreetMap (Stand des Karten-Exports, ohne
 * Gewähr - Aushang am Eingang und hagenbeck.de gehen vor). */
export const OEFFNUNG = {
  quelle: 'laut OpenStreetMap, ohne Gewähr',
  regeln: [
    { monate: [1, 2], zeit: '9:00 bis 16:30 Uhr' },
    { monate: [3, 4, 5, 6], zeit: '9:00 bis 18:00 Uhr' },
    { monate: [7, 8], zeit: '9:00 bis 19:00 Uhr' },
    { vonTag: [9, 1], bisTag: [10, 25], zeit: '9:00 bis 18:00 Uhr' },
    { vonTag: [10, 26], bisTag: [12, 31], zeit: '9:00 bis 16:30 Uhr' },
  ],
  sondertage: { '24.12.': '9:00 bis 13:00 Uhr', '31.12.': '9:00 bis 13:00 Uhr' },
};

export const WISSEN = [
  {
    titel: 'Warum es hier kaum Gitter gibt',
    text:
      'Carl Hagenbeck liess sich 1896 ein Prinzip patentieren, das Tiergärten weltweit verändert hat: Statt Gittern trennen breite, von vorn unsichtbare Gräben die Tiere von den Besuchern und voneinander. Dadurch entsteht der Eindruck einer einzigen Landschaft, in der mehrere Arten hintereinander stehen. Der Tierpark in Stellingen wurde 1907 nach diesem Prinzip eröffnet und war der erste seiner Art.',
  },
  {
    titel: 'Ein Park in Familienhand',
    text:
      'Der Tierpark wird bis heute von der Familie Hagenbeck geführt und ist damit einer der wenigen großen Zoos Europas in privater Hand. Nach der Zerstörung im Zweiten Weltkrieg wurde der Park wieder aufgebaut; das Tropen-Aquarium kam 2007 dazu, das Eismeer 2012.',
  },
  {
    titel: 'Wie man einen Zoobesuch plant',
    text:
      'Drei Dinge machen den größten Unterschied: früh kommen, die Fütterungszeiten als Fixpunkte in den Tag legen und einen Rundweg festlegen statt kreuz und quer zu laufen. Wer mit Kindern unterwegs ist, plant Pausen fest ein - die Wege summieren sich schnell auf mehrere Kilometer.',
  },
  {
    titel: 'Warum Tiere schlafen, wenn du da bist',
    text:
      'Viele Besucher kommen mittags - genau dann, wenn die meisten Tiere ruhen. Grosskatzen schlafen bis zu 20 Stunden am Tag, Ruhephasen sind bei ihnen normal und kein Zeichen von Langeweile. Wer Aktivität sehen will, kommt zur Öffnungszeit oder in der letzten Stunde vor Schluss.',
  },
  {
    titel: 'Bitte nicht füttern',
    text:
      'Mitgebrachtes Futter kann Tiere ernsthaft krank machen - auch scheinbar Harmloses wie Brot. Wo Füttern erlaubt ist, gibt es Futterautomaten des Parks mit passendem Futter. Ebenso wichtig: nicht an Scheiben klopfen und nichts in Anlagen werfen.',
  },
];
